language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build winthrop-client-ruby.gemspec
  - gem install ./winthrop-client-ruby-1.6.0.gem
