=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.34.0

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for WinthropClient::DossierApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DossierApi' do
  before do
    # run before each test
    @api_instance = WinthropClient::DossierApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DossierApi' do
    it 'should create an instance of DossierApi' do
      expect(@api_instance).to be_instance_of(WinthropClient::DossierApi)
    end
  end

  # unit tests for university_dossier_report_dossier_winad_id_get
  # University Dossier Report
  # @param winad_id 
  # @param [Hash] opts the optional parameters
  # @return [DossierReportResponse]
  describe 'university_dossier_report_dossier_winad_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
