=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.56

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::AthleticProfileShowSportHistory
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::AthleticProfileShowSportHistory do
  # let(:instance) { WinthropClient::AthleticProfileShowSportHistory.new }

  describe 'test an instance of AthleticProfileShowSportHistory' do
    it 'should create an instance of AthleticProfileShowSportHistory' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::AthleticProfileShowSportHistory)
    end
  end

  describe 'test attribute "season_year"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "conference_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "results_lens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["NET", "RPI"])
      # validator.allowable_values.each do |value|
      #   expect { instance.results_lens = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "seasons"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "churn"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "as_of"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
