=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::CoachCompensationTabComparisons
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::CoachCompensationTabComparisons do
  # let(:instance) { WinthropClient::CoachCompensationTabComparisons.new }

  describe 'test an instance of CoachCompensationTabComparisons' do
    it 'should create an instance of CoachCompensationTabComparisons' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::CoachCompensationTabComparisons)
    end
  end

  describe 'test attribute "conference"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "division"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
