=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.21.4

Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::CompareColi422Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::CompareColi422Response do
  let(:instance) { WinthropClient::CompareColi422Response.new }

  describe 'test an instance of CompareColi422Response' do
    it 'should create an instance of CompareColi422Response' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::CompareColi422Response)
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
