=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::CreateGameRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::CreateGameRequest do
  # let(:instance) { WinthropClient::CreateGameRequest.new }

  describe 'test an instance of CreateGameRequest' do
    it 'should create an instance of CreateGameRequest' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::CreateGameRequest)
    end
  end

  describe 'test attribute "game"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
