=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.4

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::CreateAdminDeskReport503Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::CreateAdminDeskReport503Response do
  # let(:instance) { WinthropClient::CreateAdminDeskReport503Response.new }

  describe 'test an instance of CreateAdminDeskReport503Response' do
    it 'should create an instance of CreateAdminDeskReport503Response' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::CreateAdminDeskReport503Response)
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "draft_uuid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
