=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.56-dev.10080

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::DepartmentCoachesQuadrant
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::DepartmentCoachesQuadrant do
  # let(:instance) { WinthropClient::DepartmentCoachesQuadrant.new }

  describe 'test an instance of DepartmentCoachesQuadrant' do
    it 'should create an instance of DepartmentCoachesQuadrant' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::DepartmentCoachesQuadrant)
    end
  end

  describe 'test attribute "spend_fiscal_year"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "spend_cohort"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["national_division"])
      # validator.allowable_values.each do |value|
      #   expect { instance.spend_cohort = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "plotted_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "seat_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
