=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.53-dev.10206

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::DepartmentGuaranteesAgreement
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::DepartmentGuaranteesAgreement do
  # let(:instance) { WinthropClient::DepartmentGuaranteesAgreement.new }

  describe 'test an instance of DepartmentGuaranteesAgreement' do
    it 'should create an instance of DepartmentGuaranteesAgreement' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::DepartmentGuaranteesAgreement)
    end
  end

  describe 'test attribute "game_contract_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "direction"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["out", "in"])
      # validator.allowable_values.each do |value|
      #   expect { instance.direction = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "opponent"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "game_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "game_date_tbd"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "comp_cents"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "comp_tbd"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "has_document"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "belongs_to_series"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
