=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.8-dev.10620

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::DeskActivityMetaSourceCoverage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::DeskActivityMetaSourceCoverage do
  # let(:instance) { WinthropClient::DeskActivityMetaSourceCoverage.new }

  describe 'test an instance of DeskActivityMetaSourceCoverage' do
    it 'should create an instance of DeskActivityMetaSourceCoverage' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::DeskActivityMetaSourceCoverage)
    end
  end

  describe 'test attribute "reasons"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["before_publication", "maximum_range", "schema_coverage", "source_retention", "ingestion_delay_possible", "legacy_events", "legacy_file_identity", "missing_version_context"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reasons = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "available_from"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "retained_from"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "retention_days"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "source_events"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "unknown_events"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "legacy_file_events"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "missing_version_events"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
