=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.16-dev.9909

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::GamePostGapCountCollectionDataInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::GamePostGapCountCollectionDataInner do
  # let(:instance) { WinthropClient::GamePostGapCountCollectionDataInner.new }

  describe 'test an instance of GamePostGapCountCollectionDataInner' do
    it 'should create an instance of GamePostGapCountCollectionDataInner' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::GamePostGapCountCollectionDataInner)
    end
  end

  describe 'test attribute "start_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
