=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::GetFavoritesCategories200ResponseInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::GetFavoritesCategories200ResponseInner do
  # let(:instance) { WinthropClient::GetFavoritesCategories200ResponseInner.new }

  describe 'test an instance of GetFavoritesCategories200ResponseInner' do
    it 'should create an instance of GetFavoritesCategories200ResponseInner' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::GetFavoritesCategories200ResponseInner)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
