=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.52

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::JobPostDisagreementCollection
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::JobPostDisagreementCollection do
  # let(:instance) { WinthropClient::JobPostDisagreementCollection.new }

  describe 'test an instance of JobPostDisagreementCollection' do
    it 'should create an instance of JobPostDisagreementCollection' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::JobPostDisagreementCollection)
    end
  end

  describe 'test attribute "new"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "new_truncated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "new_total_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "still_pending"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "still_pending_truncated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "still_pending_total_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
