=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.45.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WinthropClient::TeamSchedulePlayerDataReturningPct
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WinthropClient::TeamSchedulePlayerDataReturningPct do
  # let(:instance) { WinthropClient::TeamSchedulePlayerDataReturningPct.new }

  describe 'test an instance of TeamSchedulePlayerDataReturningPct' do
    it 'should create an instance of TeamSchedulePlayerDataReturningPct' do
      # uncomment below to test the instance creation
      # expect(instance).to be_instance_of(WinthropClient::TeamSchedulePlayerDataReturningPct)
    end
  end

  describe 'test attribute "points"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "rebounds"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "assists"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
