=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.0.0-dev.28006593744

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

module WinthropClient
  VERSION = '0.0.0-dev.28006593744'
end
