=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.40.0

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

module WinthropClient
  VERSION = '1.40.0'
end
