=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.56

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class AthleticProfileShowSportFinancialsCostPerWin < ApiModelBase
    attr_accessor :bench_cents

    attr_accessor :wins

    attr_accessor :per_win_cents

    attr_accessor :cohort_median_per_win_cents

    attr_accessor :cohort_size

    attr_accessor :cheapest

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bench_cents' => :'bench_cents',
        :'wins' => :'wins',
        :'per_win_cents' => :'per_win_cents',
        :'cohort_median_per_win_cents' => :'cohort_median_per_win_cents',
        :'cohort_size' => :'cohort_size',
        :'cheapest' => :'cheapest'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'bench_cents' => :'Integer',
        :'wins' => :'Integer',
        :'per_win_cents' => :'Integer',
        :'cohort_median_per_win_cents' => :'Integer',
        :'cohort_size' => :'Integer',
        :'cheapest' => :'AthleticProfileShowSportFinancialsCostPerWinCheapest'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'cohort_median_per_win_cents',
        :'cheapest'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::AthleticProfileShowSportFinancialsCostPerWin` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::AthleticProfileShowSportFinancialsCostPerWin`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'bench_cents')
        self.bench_cents = attributes[:'bench_cents']
      end

      if attributes.key?(:'wins')
        self.wins = attributes[:'wins']
      end

      if attributes.key?(:'per_win_cents')
        self.per_win_cents = attributes[:'per_win_cents']
      end

      if attributes.key?(:'cohort_median_per_win_cents')
        self.cohort_median_per_win_cents = attributes[:'cohort_median_per_win_cents']
      end

      if attributes.key?(:'cohort_size')
        self.cohort_size = attributes[:'cohort_size']
      end

      if attributes.key?(:'cheapest')
        self.cheapest = attributes[:'cheapest']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bench_cents == o.bench_cents &&
          wins == o.wins &&
          per_win_cents == o.per_win_cents &&
          cohort_median_per_win_cents == o.cohort_median_per_win_cents &&
          cohort_size == o.cohort_size &&
          cheapest == o.cheapest
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [bench_cents, wins, per_win_cents, cohort_median_per_win_cents, cohort_size, cheapest].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
