=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10297

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class AthleticProfileShowSportGuaranteesQuadrantPointsInner < ApiModelBase
    attr_accessor :school_id

    attr_accessor :name

    attr_accessor :short_name

    attr_accessor :colors

    attr_accessor :is_subject

    attr_accessor :bought_cents

    attr_accessor :bought_count

    attr_accessor :net_rank

    attr_accessor :rpi

    attr_accessor :conference_wins

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'school_id' => :'school_id',
        :'name' => :'name',
        :'short_name' => :'short_name',
        :'colors' => :'colors',
        :'is_subject' => :'is_subject',
        :'bought_cents' => :'bought_cents',
        :'bought_count' => :'bought_count',
        :'net_rank' => :'net_rank',
        :'rpi' => :'rpi',
        :'conference_wins' => :'conference_wins'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'school_id' => :'Integer',
        :'name' => :'String',
        :'short_name' => :'String',
        :'colors' => :'String',
        :'is_subject' => :'Boolean',
        :'bought_cents' => :'Integer',
        :'bought_count' => :'Integer',
        :'net_rank' => :'Integer',
        :'rpi' => :'Integer',
        :'conference_wins' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'colors',
        :'bought_cents',
        :'net_rank',
        :'rpi',
        :'conference_wins'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::AthleticProfileShowSportGuaranteesQuadrantPointsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::AthleticProfileShowSportGuaranteesQuadrantPointsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'school_id')
        self.school_id = attributes[:'school_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'short_name')
        self.short_name = attributes[:'short_name']
      end

      if attributes.key?(:'colors')
        self.colors = attributes[:'colors']
      end

      if attributes.key?(:'is_subject')
        self.is_subject = attributes[:'is_subject']
      end

      if attributes.key?(:'bought_cents')
        self.bought_cents = attributes[:'bought_cents']
      end

      if attributes.key?(:'bought_count')
        self.bought_count = attributes[:'bought_count']
      end

      if attributes.key?(:'net_rank')
        self.net_rank = attributes[:'net_rank']
      end

      if attributes.key?(:'rpi')
        self.rpi = attributes[:'rpi']
      end

      if attributes.key?(:'conference_wins')
        self.conference_wins = attributes[:'conference_wins']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          school_id == o.school_id &&
          name == o.name &&
          short_name == o.short_name &&
          colors == o.colors &&
          is_subject == o.is_subject &&
          bought_cents == o.bought_cents &&
          bought_count == o.bought_count &&
          net_rank == o.net_rank &&
          rpi == o.rpi &&
          conference_wins == o.conference_wins
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [school_id, name, short_name, colors, is_subject, bought_cents, bought_count, net_rank, rpi, conference_wins].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
