=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class CoachProfile < ApiModelBase
    attr_accessor :id

    attr_accessor :first_name

    attr_accessor :last_name

    attr_accessor :email

    attr_accessor :phone

    attr_accessor :leader

    attr_accessor :hometown_city

    attr_accessor :hometown_state

    attr_accessor :alma_mater_name

    attr_accessor :alma_mater_year

    attr_accessor :twitter_handle

    attr_accessor :twitter_verified

    attr_accessor :linkedin

    attr_accessor :linkedin_verified

    attr_accessor :instagram_handle

    attr_accessor :instagram_verified

    attr_accessor :bio

    attr_accessor :coach_friendly_id

    attr_accessor :departing

    attr_accessor :current_school_name

    attr_accessor :current_school_id

    attr_accessor :current_sport_name

    attr_accessor :current_position_types

    attr_accessor :avatar_url

    attr_accessor :can_see_compensation

    attr_accessor :can_see_videos

    attr_accessor :can_see_coworker_history

    attr_accessor :can_see_recruiting

    attr_accessor :is_sport_specific

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'email' => :'email',
        :'phone' => :'phone',
        :'leader' => :'leader',
        :'hometown_city' => :'hometown_city',
        :'hometown_state' => :'hometown_state',
        :'alma_mater_name' => :'alma_mater_name',
        :'alma_mater_year' => :'alma_mater_year',
        :'twitter_handle' => :'twitter_handle',
        :'twitter_verified' => :'twitter_verified',
        :'linkedin' => :'linkedin',
        :'linkedin_verified' => :'linkedin_verified',
        :'instagram_handle' => :'instagram_handle',
        :'instagram_verified' => :'instagram_verified',
        :'bio' => :'bio',
        :'coach_friendly_id' => :'coach_friendly_id',
        :'departing' => :'departing',
        :'current_school_name' => :'current_school_name',
        :'current_school_id' => :'current_school_id',
        :'current_sport_name' => :'current_sport_name',
        :'current_position_types' => :'current_position_types',
        :'avatar_url' => :'avatar_url',
        :'can_see_compensation' => :'can_see_compensation',
        :'can_see_videos' => :'can_see_videos',
        :'can_see_coworker_history' => :'can_see_coworker_history',
        :'can_see_recruiting' => :'can_see_recruiting',
        :'is_sport_specific' => :'is_sport_specific'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'email' => :'String',
        :'phone' => :'String',
        :'leader' => :'Boolean',
        :'hometown_city' => :'String',
        :'hometown_state' => :'String',
        :'alma_mater_name' => :'String',
        :'alma_mater_year' => :'Integer',
        :'twitter_handle' => :'String',
        :'twitter_verified' => :'Boolean',
        :'linkedin' => :'String',
        :'linkedin_verified' => :'Boolean',
        :'instagram_handle' => :'String',
        :'instagram_verified' => :'Boolean',
        :'bio' => :'String',
        :'coach_friendly_id' => :'String',
        :'departing' => :'Boolean',
        :'current_school_name' => :'String',
        :'current_school_id' => :'Integer',
        :'current_sport_name' => :'String',
        :'current_position_types' => :'Array<String>',
        :'avatar_url' => :'String',
        :'can_see_compensation' => :'Boolean',
        :'can_see_videos' => :'Boolean',
        :'can_see_coworker_history' => :'Boolean',
        :'can_see_recruiting' => :'Boolean',
        :'is_sport_specific' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'email',
        :'phone',
        :'hometown_city',
        :'hometown_state',
        :'alma_mater_name',
        :'alma_mater_year',
        :'twitter_handle',
        :'linkedin',
        :'instagram_handle',
        :'bio',
        :'coach_friendly_id',
        :'departing',
        :'current_school_name',
        :'current_school_id',
        :'current_sport_name',
        :'avatar_url',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::CoachProfile` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::CoachProfile`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      else
        self.first_name = nil
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      else
        self.last_name = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'leader')
        self.leader = attributes[:'leader']
      else
        self.leader = nil
      end

      if attributes.key?(:'hometown_city')
        self.hometown_city = attributes[:'hometown_city']
      end

      if attributes.key?(:'hometown_state')
        self.hometown_state = attributes[:'hometown_state']
      end

      if attributes.key?(:'alma_mater_name')
        self.alma_mater_name = attributes[:'alma_mater_name']
      end

      if attributes.key?(:'alma_mater_year')
        self.alma_mater_year = attributes[:'alma_mater_year']
      end

      if attributes.key?(:'twitter_handle')
        self.twitter_handle = attributes[:'twitter_handle']
      end

      if attributes.key?(:'twitter_verified')
        self.twitter_verified = attributes[:'twitter_verified']
      else
        self.twitter_verified = nil
      end

      if attributes.key?(:'linkedin')
        self.linkedin = attributes[:'linkedin']
      end

      if attributes.key?(:'linkedin_verified')
        self.linkedin_verified = attributes[:'linkedin_verified']
      else
        self.linkedin_verified = nil
      end

      if attributes.key?(:'instagram_handle')
        self.instagram_handle = attributes[:'instagram_handle']
      end

      if attributes.key?(:'instagram_verified')
        self.instagram_verified = attributes[:'instagram_verified']
      else
        self.instagram_verified = nil
      end

      if attributes.key?(:'bio')
        self.bio = attributes[:'bio']
      end

      if attributes.key?(:'coach_friendly_id')
        self.coach_friendly_id = attributes[:'coach_friendly_id']
      end

      if attributes.key?(:'departing')
        self.departing = attributes[:'departing']
      end

      if attributes.key?(:'current_school_name')
        self.current_school_name = attributes[:'current_school_name']
      end

      if attributes.key?(:'current_school_id')
        self.current_school_id = attributes[:'current_school_id']
      end

      if attributes.key?(:'current_sport_name')
        self.current_sport_name = attributes[:'current_sport_name']
      end

      if attributes.key?(:'current_position_types')
        if (value = attributes[:'current_position_types']).is_a?(Array)
          self.current_position_types = value
        end
      else
        self.current_position_types = nil
      end

      if attributes.key?(:'avatar_url')
        self.avatar_url = attributes[:'avatar_url']
      end

      if attributes.key?(:'can_see_compensation')
        self.can_see_compensation = attributes[:'can_see_compensation']
      else
        self.can_see_compensation = nil
      end

      if attributes.key?(:'can_see_videos')
        self.can_see_videos = attributes[:'can_see_videos']
      else
        self.can_see_videos = nil
      end

      if attributes.key?(:'can_see_coworker_history')
        self.can_see_coworker_history = attributes[:'can_see_coworker_history']
      else
        self.can_see_coworker_history = nil
      end

      if attributes.key?(:'can_see_recruiting')
        self.can_see_recruiting = attributes[:'can_see_recruiting']
      else
        self.can_see_recruiting = nil
      end

      if attributes.key?(:'is_sport_specific')
        self.is_sport_specific = attributes[:'is_sport_specific']
      else
        self.is_sport_specific = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @first_name.nil?
        invalid_properties.push('invalid value for "first_name", first_name cannot be nil.')
      end

      if @last_name.nil?
        invalid_properties.push('invalid value for "last_name", last_name cannot be nil.')
      end

      if @leader.nil?
        invalid_properties.push('invalid value for "leader", leader cannot be nil.')
      end

      if @twitter_verified.nil?
        invalid_properties.push('invalid value for "twitter_verified", twitter_verified cannot be nil.')
      end

      if @linkedin_verified.nil?
        invalid_properties.push('invalid value for "linkedin_verified", linkedin_verified cannot be nil.')
      end

      if @instagram_verified.nil?
        invalid_properties.push('invalid value for "instagram_verified", instagram_verified cannot be nil.')
      end

      if @current_position_types.nil?
        invalid_properties.push('invalid value for "current_position_types", current_position_types cannot be nil.')
      end

      if @can_see_compensation.nil?
        invalid_properties.push('invalid value for "can_see_compensation", can_see_compensation cannot be nil.')
      end

      if @can_see_videos.nil?
        invalid_properties.push('invalid value for "can_see_videos", can_see_videos cannot be nil.')
      end

      if @can_see_coworker_history.nil?
        invalid_properties.push('invalid value for "can_see_coworker_history", can_see_coworker_history cannot be nil.')
      end

      if @can_see_recruiting.nil?
        invalid_properties.push('invalid value for "can_see_recruiting", can_see_recruiting cannot be nil.')
      end

      if @is_sport_specific.nil?
        invalid_properties.push('invalid value for "is_sport_specific", is_sport_specific cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @first_name.nil?
      return false if @last_name.nil?
      return false if @leader.nil?
      return false if @twitter_verified.nil?
      return false if @linkedin_verified.nil?
      return false if @instagram_verified.nil?
      return false if @current_position_types.nil?
      return false if @can_see_compensation.nil?
      return false if @can_see_videos.nil?
      return false if @can_see_coworker_history.nil?
      return false if @can_see_recruiting.nil?
      return false if @is_sport_specific.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] first_name Value to be assigned
    def first_name=(first_name)
      if first_name.nil?
        fail ArgumentError, 'first_name cannot be nil'
      end

      @first_name = first_name
    end

    # Custom attribute writer method with validation
    # @param [Object] last_name Value to be assigned
    def last_name=(last_name)
      if last_name.nil?
        fail ArgumentError, 'last_name cannot be nil'
      end

      @last_name = last_name
    end

    # Custom attribute writer method with validation
    # @param [Object] leader Value to be assigned
    def leader=(leader)
      if leader.nil?
        fail ArgumentError, 'leader cannot be nil'
      end

      @leader = leader
    end

    # Custom attribute writer method with validation
    # @param [Object] twitter_verified Value to be assigned
    def twitter_verified=(twitter_verified)
      if twitter_verified.nil?
        fail ArgumentError, 'twitter_verified cannot be nil'
      end

      @twitter_verified = twitter_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] linkedin_verified Value to be assigned
    def linkedin_verified=(linkedin_verified)
      if linkedin_verified.nil?
        fail ArgumentError, 'linkedin_verified cannot be nil'
      end

      @linkedin_verified = linkedin_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] instagram_verified Value to be assigned
    def instagram_verified=(instagram_verified)
      if instagram_verified.nil?
        fail ArgumentError, 'instagram_verified cannot be nil'
      end

      @instagram_verified = instagram_verified
    end

    # Custom attribute writer method with validation
    # @param [Object] current_position_types Value to be assigned
    def current_position_types=(current_position_types)
      if current_position_types.nil?
        fail ArgumentError, 'current_position_types cannot be nil'
      end

      @current_position_types = current_position_types
    end

    # Custom attribute writer method with validation
    # @param [Object] can_see_compensation Value to be assigned
    def can_see_compensation=(can_see_compensation)
      if can_see_compensation.nil?
        fail ArgumentError, 'can_see_compensation cannot be nil'
      end

      @can_see_compensation = can_see_compensation
    end

    # Custom attribute writer method with validation
    # @param [Object] can_see_videos Value to be assigned
    def can_see_videos=(can_see_videos)
      if can_see_videos.nil?
        fail ArgumentError, 'can_see_videos cannot be nil'
      end

      @can_see_videos = can_see_videos
    end

    # Custom attribute writer method with validation
    # @param [Object] can_see_coworker_history Value to be assigned
    def can_see_coworker_history=(can_see_coworker_history)
      if can_see_coworker_history.nil?
        fail ArgumentError, 'can_see_coworker_history cannot be nil'
      end

      @can_see_coworker_history = can_see_coworker_history
    end

    # Custom attribute writer method with validation
    # @param [Object] can_see_recruiting Value to be assigned
    def can_see_recruiting=(can_see_recruiting)
      if can_see_recruiting.nil?
        fail ArgumentError, 'can_see_recruiting cannot be nil'
      end

      @can_see_recruiting = can_see_recruiting
    end

    # Custom attribute writer method with validation
    # @param [Object] is_sport_specific Value to be assigned
    def is_sport_specific=(is_sport_specific)
      if is_sport_specific.nil?
        fail ArgumentError, 'is_sport_specific cannot be nil'
      end

      @is_sport_specific = is_sport_specific
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          email == o.email &&
          phone == o.phone &&
          leader == o.leader &&
          hometown_city == o.hometown_city &&
          hometown_state == o.hometown_state &&
          alma_mater_name == o.alma_mater_name &&
          alma_mater_year == o.alma_mater_year &&
          twitter_handle == o.twitter_handle &&
          twitter_verified == o.twitter_verified &&
          linkedin == o.linkedin &&
          linkedin_verified == o.linkedin_verified &&
          instagram_handle == o.instagram_handle &&
          instagram_verified == o.instagram_verified &&
          bio == o.bio &&
          coach_friendly_id == o.coach_friendly_id &&
          departing == o.departing &&
          current_school_name == o.current_school_name &&
          current_school_id == o.current_school_id &&
          current_sport_name == o.current_sport_name &&
          current_position_types == o.current_position_types &&
          avatar_url == o.avatar_url &&
          can_see_compensation == o.can_see_compensation &&
          can_see_videos == o.can_see_videos &&
          can_see_coworker_history == o.can_see_coworker_history &&
          can_see_recruiting == o.can_see_recruiting &&
          is_sport_specific == o.is_sport_specific
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, first_name, last_name, email, phone, leader, hometown_city, hometown_state, alma_mater_name, alma_mater_year, twitter_handle, twitter_verified, linkedin, linkedin_verified, instagram_handle, instagram_verified, bio, coach_friendly_id, departing, current_school_name, current_school_id, current_sport_name, current_position_types, avatar_url, can_see_compensation, can_see_videos, can_see_coworker_history, can_see_recruiting, is_sport_specific].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
