=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.3-dev.10480

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # Compensation resolves for the selected assignment in the system's current season, carrying forward at most two seasons within the same continuous job. History stays as reported. The snapshot is null without compensation access or a selected position. season_year_str, performance, income reports and current contract fields retain their assignment context; compensation_source_year identifies the salary's actual season. Hourly current records retain their stored values and type; no annualization occurs. 
  class CoachSnapshot < ApiModelBase
    attr_accessor :season_year_str

    # Base from the resolved compensation record, in cents; null when unavailable.
    attr_accessor :base_comp_cents

    # Guaranteed total from the same resolved record, in cents; null when unavailable.
    attr_accessor :total_comp_cents

    # Resolved record's type, or null when compensation is unavailable.
    attr_accessor :compensation_type

    # Salary source season end year; null when unavailable, never inferred from contract dates.
    attr_accessor :compensation_source_year

    # True only when salary comes from an earlier eligible season; false when unavailable.
    attr_accessor :compensation_is_fallback

    # Resolved compensation id; null when unavailable. Gated with amounts by compensation access.
    attr_accessor :compensation_source_compensation_id

    # Salary source document id; omitted unless both its contract and document are authorized.
    attr_accessor :compensation_source_raw_contract_id

    attr_accessor :buyout_terms

    attr_accessor :record

    attr_accessor :contract_start

    attr_accessor :contract_end

    attr_accessor :contract_at_will

    # Selected position's current contract document, never replaced by the salary source document.
    attr_accessor :raw_contract_id

    attr_accessor :income_reports

    attr_accessor :asst_coach_pool_cents

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'season_year_str' => :'season_year_str',
        :'base_comp_cents' => :'base_comp_cents',
        :'total_comp_cents' => :'total_comp_cents',
        :'compensation_type' => :'compensation_type',
        :'compensation_source_year' => :'compensation_source_year',
        :'compensation_is_fallback' => :'compensation_is_fallback',
        :'compensation_source_compensation_id' => :'compensation_source_compensation_id',
        :'compensation_source_raw_contract_id' => :'compensation_source_raw_contract_id',
        :'buyout_terms' => :'buyout_terms',
        :'record' => :'record',
        :'contract_start' => :'contract_start',
        :'contract_end' => :'contract_end',
        :'contract_at_will' => :'contract_at_will',
        :'raw_contract_id' => :'raw_contract_id',
        :'income_reports' => :'income_reports',
        :'asst_coach_pool_cents' => :'asst_coach_pool_cents'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'season_year_str' => :'String',
        :'base_comp_cents' => :'Integer',
        :'total_comp_cents' => :'Integer',
        :'compensation_type' => :'String',
        :'compensation_source_year' => :'Integer',
        :'compensation_is_fallback' => :'Boolean',
        :'compensation_source_compensation_id' => :'Integer',
        :'compensation_source_raw_contract_id' => :'Integer',
        :'buyout_terms' => :'String',
        :'record' => :'String',
        :'contract_start' => :'String',
        :'contract_end' => :'String',
        :'contract_at_will' => :'Boolean',
        :'raw_contract_id' => :'Integer',
        :'income_reports' => :'Array<SnapshotIncomeReport>',
        :'asst_coach_pool_cents' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'base_comp_cents',
        :'total_comp_cents',
        :'compensation_type',
        :'compensation_source_year',
        :'compensation_source_compensation_id',
        :'buyout_terms',
        :'record',
        :'contract_start',
        :'contract_end',
        :'contract_at_will',
        :'raw_contract_id',
        :'asst_coach_pool_cents'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::CoachSnapshot` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::CoachSnapshot`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'season_year_str')
        self.season_year_str = attributes[:'season_year_str']
      else
        self.season_year_str = nil
      end

      if attributes.key?(:'base_comp_cents')
        self.base_comp_cents = attributes[:'base_comp_cents']
      else
        self.base_comp_cents = nil
      end

      if attributes.key?(:'total_comp_cents')
        self.total_comp_cents = attributes[:'total_comp_cents']
      else
        self.total_comp_cents = nil
      end

      if attributes.key?(:'compensation_type')
        self.compensation_type = attributes[:'compensation_type']
      else
        self.compensation_type = nil
      end

      if attributes.key?(:'compensation_source_year')
        self.compensation_source_year = attributes[:'compensation_source_year']
      else
        self.compensation_source_year = nil
      end

      if attributes.key?(:'compensation_is_fallback')
        self.compensation_is_fallback = attributes[:'compensation_is_fallback']
      else
        self.compensation_is_fallback = nil
      end

      if attributes.key?(:'compensation_source_compensation_id')
        self.compensation_source_compensation_id = attributes[:'compensation_source_compensation_id']
      else
        self.compensation_source_compensation_id = nil
      end

      if attributes.key?(:'compensation_source_raw_contract_id')
        self.compensation_source_raw_contract_id = attributes[:'compensation_source_raw_contract_id']
      end

      if attributes.key?(:'buyout_terms')
        self.buyout_terms = attributes[:'buyout_terms']
      else
        self.buyout_terms = nil
      end

      if attributes.key?(:'record')
        self.record = attributes[:'record']
      end

      if attributes.key?(:'contract_start')
        self.contract_start = attributes[:'contract_start']
      end

      if attributes.key?(:'contract_end')
        self.contract_end = attributes[:'contract_end']
      end

      if attributes.key?(:'contract_at_will')
        self.contract_at_will = attributes[:'contract_at_will']
      end

      if attributes.key?(:'raw_contract_id')
        self.raw_contract_id = attributes[:'raw_contract_id']
      end

      if attributes.key?(:'income_reports')
        if (value = attributes[:'income_reports']).is_a?(Array)
          self.income_reports = value
        end
      end

      if attributes.key?(:'asst_coach_pool_cents')
        self.asst_coach_pool_cents = attributes[:'asst_coach_pool_cents']
      else
        self.asst_coach_pool_cents = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @season_year_str.nil?
        invalid_properties.push('invalid value for "season_year_str", season_year_str cannot be nil.')
      end

      if @compensation_is_fallback.nil?
        invalid_properties.push('invalid value for "compensation_is_fallback", compensation_is_fallback cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @season_year_str.nil?
      return false if @compensation_is_fallback.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] season_year_str Value to be assigned
    def season_year_str=(season_year_str)
      if season_year_str.nil?
        fail ArgumentError, 'season_year_str cannot be nil'
      end

      @season_year_str = season_year_str
    end

    # Custom attribute writer method with validation
    # @param [Object] compensation_is_fallback Value to be assigned
    def compensation_is_fallback=(compensation_is_fallback)
      if compensation_is_fallback.nil?
        fail ArgumentError, 'compensation_is_fallback cannot be nil'
      end

      @compensation_is_fallback = compensation_is_fallback
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          season_year_str == o.season_year_str &&
          base_comp_cents == o.base_comp_cents &&
          total_comp_cents == o.total_comp_cents &&
          compensation_type == o.compensation_type &&
          compensation_source_year == o.compensation_source_year &&
          compensation_is_fallback == o.compensation_is_fallback &&
          compensation_source_compensation_id == o.compensation_source_compensation_id &&
          compensation_source_raw_contract_id == o.compensation_source_raw_contract_id &&
          buyout_terms == o.buyout_terms &&
          record == o.record &&
          contract_start == o.contract_start &&
          contract_end == o.contract_end &&
          contract_at_will == o.contract_at_will &&
          raw_contract_id == o.raw_contract_id &&
          income_reports == o.income_reports &&
          asst_coach_pool_cents == o.asst_coach_pool_cents
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [season_year_str, base_comp_cents, total_comp_cents, compensation_type, compensation_source_year, compensation_is_fallback, compensation_source_compensation_id, compensation_source_raw_contract_id, buyout_terms, record, contract_start, contract_end, contract_at_will, raw_contract_id, income_reports, asst_coach_pool_cents].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
