=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.46-dev.9647

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # Class-level capability flags: whether the caller's account can see coach / administrator compensation at all, and whether administrator records were searched. Per-row visibility is carried by each row's comp_status (comp_redacted) and the cohort comp_redacted_count.
  class CompensationComparisonCompVisibility < ApiModelBase
    attr_accessor :coach_compensation

    attr_accessor :administrator_compensation

    attr_accessor :administrator_records_searched

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'coach_compensation' => :'coach_compensation',
        :'administrator_compensation' => :'administrator_compensation',
        :'administrator_records_searched' => :'administrator_records_searched'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'coach_compensation' => :'Boolean',
        :'administrator_compensation' => :'Boolean',
        :'administrator_records_searched' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::CompensationComparisonCompVisibility` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::CompensationComparisonCompVisibility`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'coach_compensation')
        self.coach_compensation = attributes[:'coach_compensation']
      else
        self.coach_compensation = nil
      end

      if attributes.key?(:'administrator_compensation')
        self.administrator_compensation = attributes[:'administrator_compensation']
      else
        self.administrator_compensation = nil
      end

      if attributes.key?(:'administrator_records_searched')
        self.administrator_records_searched = attributes[:'administrator_records_searched']
      else
        self.administrator_records_searched = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @coach_compensation.nil?
        invalid_properties.push('invalid value for "coach_compensation", coach_compensation cannot be nil.')
      end

      if @administrator_compensation.nil?
        invalid_properties.push('invalid value for "administrator_compensation", administrator_compensation cannot be nil.')
      end

      if @administrator_records_searched.nil?
        invalid_properties.push('invalid value for "administrator_records_searched", administrator_records_searched cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @coach_compensation.nil?
      return false if @administrator_compensation.nil?
      return false if @administrator_records_searched.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] coach_compensation Value to be assigned
    def coach_compensation=(coach_compensation)
      if coach_compensation.nil?
        fail ArgumentError, 'coach_compensation cannot be nil'
      end

      @coach_compensation = coach_compensation
    end

    # Custom attribute writer method with validation
    # @param [Object] administrator_compensation Value to be assigned
    def administrator_compensation=(administrator_compensation)
      if administrator_compensation.nil?
        fail ArgumentError, 'administrator_compensation cannot be nil'
      end

      @administrator_compensation = administrator_compensation
    end

    # Custom attribute writer method with validation
    # @param [Object] administrator_records_searched Value to be assigned
    def administrator_records_searched=(administrator_records_searched)
      if administrator_records_searched.nil?
        fail ArgumentError, 'administrator_records_searched cannot be nil'
      end

      @administrator_records_searched = administrator_records_searched
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          coach_compensation == o.coach_compensation &&
          administrator_compensation == o.administrator_compensation &&
          administrator_records_searched == o.administrator_records_searched
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [coach_compensation, administrator_compensation, administrator_records_searched].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
