=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # A single head coach or AD compensation record
  class CompensationRow < ApiModelBase
    attr_accessor :id

    attr_accessor :school_id

    attr_accessor :school_name

    attr_accessor :coach_id

    attr_accessor :coach_name

    attr_accessor :total_comp

    attr_accessor :base_salary

    attr_accessor :talent_fee

    attr_accessor :outside_income

    attr_accessor :contingent_bonus

    attr_accessor :car_provided

    attr_accessor :country_club

    attr_accessor :buyout_terms

    attr_accessor :contract_end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'school_id' => :'school_id',
        :'school_name' => :'school_name',
        :'coach_id' => :'coach_id',
        :'coach_name' => :'coach_name',
        :'total_comp' => :'total_comp',
        :'base_salary' => :'base_salary',
        :'talent_fee' => :'talent_fee',
        :'outside_income' => :'outside_income',
        :'contingent_bonus' => :'contingent_bonus',
        :'car_provided' => :'car_provided',
        :'country_club' => :'country_club',
        :'buyout_terms' => :'buyout_terms',
        :'contract_end' => :'contract_end'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'school_id' => :'Integer',
        :'school_name' => :'String',
        :'coach_id' => :'Integer',
        :'coach_name' => :'String',
        :'total_comp' => :'Integer',
        :'base_salary' => :'Integer',
        :'talent_fee' => :'Float',
        :'outside_income' => :'Integer',
        :'contingent_bonus' => :'Boolean',
        :'car_provided' => :'Boolean',
        :'country_club' => :'Boolean',
        :'buyout_terms' => :'String',
        :'contract_end' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'total_comp',
        :'base_salary',
        :'talent_fee',
        :'outside_income',
        :'buyout_terms',
        :'contract_end'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::CompensationRow` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::CompensationRow`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'school_id')
        self.school_id = attributes[:'school_id']
      end

      if attributes.key?(:'school_name')
        self.school_name = attributes[:'school_name']
      end

      if attributes.key?(:'coach_id')
        self.coach_id = attributes[:'coach_id']
      end

      if attributes.key?(:'coach_name')
        self.coach_name = attributes[:'coach_name']
      end

      if attributes.key?(:'total_comp')
        self.total_comp = attributes[:'total_comp']
      end

      if attributes.key?(:'base_salary')
        self.base_salary = attributes[:'base_salary']
      end

      if attributes.key?(:'talent_fee')
        self.talent_fee = attributes[:'talent_fee']
      end

      if attributes.key?(:'outside_income')
        self.outside_income = attributes[:'outside_income']
      end

      if attributes.key?(:'contingent_bonus')
        self.contingent_bonus = attributes[:'contingent_bonus']
      end

      if attributes.key?(:'car_provided')
        self.car_provided = attributes[:'car_provided']
      end

      if attributes.key?(:'country_club')
        self.country_club = attributes[:'country_club']
      end

      if attributes.key?(:'buyout_terms')
        self.buyout_terms = attributes[:'buyout_terms']
      end

      if attributes.key?(:'contract_end')
        self.contract_end = attributes[:'contract_end']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          school_id == o.school_id &&
          school_name == o.school_name &&
          coach_id == o.coach_id &&
          coach_name == o.coach_name &&
          total_comp == o.total_comp &&
          base_salary == o.base_salary &&
          talent_fee == o.talent_fee &&
          outside_income == o.outside_income &&
          contingent_bonus == o.contingent_bonus &&
          car_provided == o.car_provided &&
          country_club == o.country_club &&
          buyout_terms == o.buyout_terms &&
          contract_end == o.contract_end
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, school_id, school_name, coach_id, coach_name, total_comp, base_salary, talent_fee, outside_income, contingent_bonus, car_provided, country_club, buyout_terms, contract_end].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
