=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10377

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class DepartmentGuaranteesQuadrantPoint < ApiModelBase
    attr_accessor :school_id

    attr_accessor :name

    attr_accessor :is_subject

    attr_accessor :colors

    attr_accessor :paid_cents

    attr_accessor :received_cents

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'school_id' => :'school_id',
        :'name' => :'name',
        :'is_subject' => :'is_subject',
        :'colors' => :'colors',
        :'paid_cents' => :'paid_cents',
        :'received_cents' => :'received_cents'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'school_id' => :'Integer',
        :'name' => :'String',
        :'is_subject' => :'Boolean',
        :'colors' => :'String',
        :'paid_cents' => :'Integer',
        :'received_cents' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'colors',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::DepartmentGuaranteesQuadrantPoint` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::DepartmentGuaranteesQuadrantPoint`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'school_id')
        self.school_id = attributes[:'school_id']
      else
        self.school_id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'is_subject')
        self.is_subject = attributes[:'is_subject']
      else
        self.is_subject = nil
      end

      if attributes.key?(:'colors')
        self.colors = attributes[:'colors']
      else
        self.colors = nil
      end

      if attributes.key?(:'paid_cents')
        self.paid_cents = attributes[:'paid_cents']
      else
        self.paid_cents = nil
      end

      if attributes.key?(:'received_cents')
        self.received_cents = attributes[:'received_cents']
      else
        self.received_cents = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @school_id.nil?
        invalid_properties.push('invalid value for "school_id", school_id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @is_subject.nil?
        invalid_properties.push('invalid value for "is_subject", is_subject cannot be nil.')
      end

      if @paid_cents.nil?
        invalid_properties.push('invalid value for "paid_cents", paid_cents cannot be nil.')
      end

      if @received_cents.nil?
        invalid_properties.push('invalid value for "received_cents", received_cents cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @school_id.nil?
      return false if @name.nil?
      return false if @is_subject.nil?
      return false if @paid_cents.nil?
      return false if @received_cents.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] school_id Value to be assigned
    def school_id=(school_id)
      if school_id.nil?
        fail ArgumentError, 'school_id cannot be nil'
      end

      @school_id = school_id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] is_subject Value to be assigned
    def is_subject=(is_subject)
      if is_subject.nil?
        fail ArgumentError, 'is_subject cannot be nil'
      end

      @is_subject = is_subject
    end

    # Custom attribute writer method with validation
    # @param [Object] paid_cents Value to be assigned
    def paid_cents=(paid_cents)
      if paid_cents.nil?
        fail ArgumentError, 'paid_cents cannot be nil'
      end

      @paid_cents = paid_cents
    end

    # Custom attribute writer method with validation
    # @param [Object] received_cents Value to be assigned
    def received_cents=(received_cents)
      if received_cents.nil?
        fail ArgumentError, 'received_cents cannot be nil'
      end

      @received_cents = received_cents
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          school_id == o.school_id &&
          name == o.name &&
          is_subject == o.is_subject &&
          colors == o.colors &&
          paid_cents == o.paid_cents &&
          received_cents == o.received_cents
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [school_id, name, is_subject, colors, paid_cents, received_cents].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
