=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.66

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class DepartmentOverviewQuadrantPoint < ApiModelBase
    attr_accessor :school_id

    attr_accessor :name

    attr_accessor :is_subject

    attr_accessor :colors

    attr_accessor :exp_total_cents

    # Directors' Cup finishing position, scored within division — lower is better
    attr_accessor :cup_place

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'school_id' => :'school_id',
        :'name' => :'name',
        :'is_subject' => :'is_subject',
        :'colors' => :'colors',
        :'exp_total_cents' => :'exp_total_cents',
        :'cup_place' => :'cup_place'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'school_id' => :'Integer',
        :'name' => :'String',
        :'is_subject' => :'Boolean',
        :'colors' => :'String',
        :'exp_total_cents' => :'Integer',
        :'cup_place' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'colors',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::DepartmentOverviewQuadrantPoint` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::DepartmentOverviewQuadrantPoint`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'school_id')
        self.school_id = attributes[:'school_id']
      else
        self.school_id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'is_subject')
        self.is_subject = attributes[:'is_subject']
      else
        self.is_subject = nil
      end

      if attributes.key?(:'colors')
        self.colors = attributes[:'colors']
      else
        self.colors = nil
      end

      if attributes.key?(:'exp_total_cents')
        self.exp_total_cents = attributes[:'exp_total_cents']
      else
        self.exp_total_cents = nil
      end

      if attributes.key?(:'cup_place')
        self.cup_place = attributes[:'cup_place']
      else
        self.cup_place = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @school_id.nil?
        invalid_properties.push('invalid value for "school_id", school_id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @is_subject.nil?
        invalid_properties.push('invalid value for "is_subject", is_subject cannot be nil.')
      end

      if @exp_total_cents.nil?
        invalid_properties.push('invalid value for "exp_total_cents", exp_total_cents cannot be nil.')
      end

      if @cup_place.nil?
        invalid_properties.push('invalid value for "cup_place", cup_place cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @school_id.nil?
      return false if @name.nil?
      return false if @is_subject.nil?
      return false if @exp_total_cents.nil?
      return false if @cup_place.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] school_id Value to be assigned
    def school_id=(school_id)
      if school_id.nil?
        fail ArgumentError, 'school_id cannot be nil'
      end

      @school_id = school_id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] is_subject Value to be assigned
    def is_subject=(is_subject)
      if is_subject.nil?
        fail ArgumentError, 'is_subject cannot be nil'
      end

      @is_subject = is_subject
    end

    # Custom attribute writer method with validation
    # @param [Object] exp_total_cents Value to be assigned
    def exp_total_cents=(exp_total_cents)
      if exp_total_cents.nil?
        fail ArgumentError, 'exp_total_cents cannot be nil'
      end

      @exp_total_cents = exp_total_cents
    end

    # Custom attribute writer method with validation
    # @param [Object] cup_place Value to be assigned
    def cup_place=(cup_place)
      if cup_place.nil?
        fail ArgumentError, 'cup_place cannot be nil'
      end

      @cup_place = cup_place
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          school_id == o.school_id &&
          name == o.name &&
          is_subject == o.is_subject &&
          colors == o.colors &&
          exp_total_cents == o.exp_total_cents &&
          cup_place == o.cup_place
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [school_id, name, is_subject, colors, exp_total_cents, cup_place].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
