=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.66

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class DepartmentCoachesClockRow < ApiModelBase
    attr_accessor :sport_abbrev

    attr_accessor :group

    attr_accessor :names

    attr_accessor :people

    attr_accessor :state

    attr_accessor :date

    attr_accessor :approximate

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'sport_abbrev' => :'sport_abbrev',
        :'group' => :'group',
        :'names' => :'names',
        :'people' => :'people',
        :'state' => :'state',
        :'date' => :'date',
        :'approximate' => :'approximate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'sport_abbrev' => :'String',
        :'group' => :'String',
        :'names' => :'Array<String>',
        :'people' => :'Array<DepartmentCoachesClockRowPeopleInner>',
        :'state' => :'String',
        :'date' => :'String',
        :'approximate' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'date',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::DepartmentCoachesClockRow` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::DepartmentCoachesClockRow`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'sport_abbrev')
        self.sport_abbrev = attributes[:'sport_abbrev']
      else
        self.sport_abbrev = nil
      end

      if attributes.key?(:'group')
        self.group = attributes[:'group']
      else
        self.group = nil
      end

      if attributes.key?(:'names')
        if (value = attributes[:'names']).is_a?(Array)
          self.names = value
        end
      else
        self.names = nil
      end

      if attributes.key?(:'people')
        if (value = attributes[:'people']).is_a?(Array)
          self.people = value
        end
      else
        self.people = nil
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      else
        self.state = nil
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'approximate')
        self.approximate = attributes[:'approximate']
      else
        self.approximate = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @sport_abbrev.nil?
        invalid_properties.push('invalid value for "sport_abbrev", sport_abbrev cannot be nil.')
      end

      if @group.nil?
        invalid_properties.push('invalid value for "group", group cannot be nil.')
      end

      if @names.nil?
        invalid_properties.push('invalid value for "names", names cannot be nil.')
      end

      if @people.nil?
        invalid_properties.push('invalid value for "people", people cannot be nil.')
      end

      if @state.nil?
        invalid_properties.push('invalid value for "state", state cannot be nil.')
      end

      if @approximate.nil?
        invalid_properties.push('invalid value for "approximate", approximate cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @sport_abbrev.nil?
      return false if @group.nil?
      group_validator = EnumAttributeValidator.new('String', ["head", "assistants"])
      return false unless group_validator.valid?(@group)
      return false if @names.nil?
      return false if @people.nil?
      return false if @state.nil?
      state_validator = EnumAttributeValidator.new('String', ["expires", "renewal_window", "at_will", "extended", "none_on_file"])
      return false unless state_validator.valid?(@state)
      return false if @approximate.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] sport_abbrev Value to be assigned
    def sport_abbrev=(sport_abbrev)
      if sport_abbrev.nil?
        fail ArgumentError, 'sport_abbrev cannot be nil'
      end

      @sport_abbrev = sport_abbrev
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] group Object to be assigned
    def group=(group)
      validator = EnumAttributeValidator.new('String', ["head", "assistants"])
      unless validator.valid?(group)
        fail ArgumentError, "invalid value for \"group\", must be one of #{validator.allowable_values}."
      end
      @group = group
    end

    # Custom attribute writer method with validation
    # @param [Object] names Value to be assigned
    def names=(names)
      if names.nil?
        fail ArgumentError, 'names cannot be nil'
      end

      @names = names
    end

    # Custom attribute writer method with validation
    # @param [Object] people Value to be assigned
    def people=(people)
      if people.nil?
        fail ArgumentError, 'people cannot be nil'
      end

      @people = people
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('String', ["expires", "renewal_window", "at_will", "extended", "none_on_file"])
      unless validator.valid?(state)
        fail ArgumentError, "invalid value for \"state\", must be one of #{validator.allowable_values}."
      end
      @state = state
    end

    # Custom attribute writer method with validation
    # @param [Object] approximate Value to be assigned
    def approximate=(approximate)
      if approximate.nil?
        fail ArgumentError, 'approximate cannot be nil'
      end

      @approximate = approximate
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          sport_abbrev == o.sport_abbrev &&
          group == o.group &&
          names == o.names &&
          people == o.people &&
          state == o.state &&
          date == o.date &&
          approximate == o.approximate
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [sport_abbrev, group, names, people, state, date, approximate].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
