=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class DepartmentCoachSeat < ApiModelBase
    attr_accessor :sport

    attr_accessor :coach

    attr_accessor :pay

    attr_accessor :result

    attr_accessor :verdict

    attr_accessor :quadrant_point

    attr_accessor :unplotted_reason

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'sport' => :'sport',
        :'coach' => :'coach',
        :'pay' => :'pay',
        :'result' => :'result',
        :'verdict' => :'verdict',
        :'quadrant_point' => :'quadrant_point',
        :'unplotted_reason' => :'unplotted_reason'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'sport' => :'DepartmentCoachSeatSport',
        :'coach' => :'DepartmentCoachSeatCoach',
        :'pay' => :'DepartmentCoachPay',
        :'result' => :'DepartmentCoachResult',
        :'verdict' => :'DepartmentCoachVerdict',
        :'quadrant_point' => :'DepartmentCoachQuadrantPoint',
        :'unplotted_reason' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'quadrant_point',
        :'unplotted_reason'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::DepartmentCoachSeat` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::DepartmentCoachSeat`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'sport')
        self.sport = attributes[:'sport']
      else
        self.sport = nil
      end

      if attributes.key?(:'coach')
        self.coach = attributes[:'coach']
      else
        self.coach = nil
      end

      if attributes.key?(:'pay')
        self.pay = attributes[:'pay']
      else
        self.pay = nil
      end

      if attributes.key?(:'result')
        self.result = attributes[:'result']
      else
        self.result = nil
      end

      if attributes.key?(:'verdict')
        self.verdict = attributes[:'verdict']
      else
        self.verdict = nil
      end

      if attributes.key?(:'quadrant_point')
        self.quadrant_point = attributes[:'quadrant_point']
      else
        self.quadrant_point = nil
      end

      if attributes.key?(:'unplotted_reason')
        self.unplotted_reason = attributes[:'unplotted_reason']
      else
        self.unplotted_reason = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @sport.nil?
        invalid_properties.push('invalid value for "sport", sport cannot be nil.')
      end

      if @coach.nil?
        invalid_properties.push('invalid value for "coach", coach cannot be nil.')
      end

      if @pay.nil?
        invalid_properties.push('invalid value for "pay", pay cannot be nil.')
      end

      if @result.nil?
        invalid_properties.push('invalid value for "result", result cannot be nil.')
      end

      if @verdict.nil?
        invalid_properties.push('invalid value for "verdict", verdict cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @sport.nil?
      return false if @coach.nil?
      return false if @pay.nil?
      return false if @result.nil?
      return false if @verdict.nil?
      unplotted_reason_validator = EnumAttributeValidator.new('String', ["no_sport_financials", "no_ranked_result"])
      return false unless unplotted_reason_validator.valid?(@unplotted_reason)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] sport Value to be assigned
    def sport=(sport)
      if sport.nil?
        fail ArgumentError, 'sport cannot be nil'
      end

      @sport = sport
    end

    # Custom attribute writer method with validation
    # @param [Object] coach Value to be assigned
    def coach=(coach)
      if coach.nil?
        fail ArgumentError, 'coach cannot be nil'
      end

      @coach = coach
    end

    # Custom attribute writer method with validation
    # @param [Object] pay Value to be assigned
    def pay=(pay)
      if pay.nil?
        fail ArgumentError, 'pay cannot be nil'
      end

      @pay = pay
    end

    # Custom attribute writer method with validation
    # @param [Object] result Value to be assigned
    def result=(result)
      if result.nil?
        fail ArgumentError, 'result cannot be nil'
      end

      @result = result
    end

    # Custom attribute writer method with validation
    # @param [Object] verdict Value to be assigned
    def verdict=(verdict)
      if verdict.nil?
        fail ArgumentError, 'verdict cannot be nil'
      end

      @verdict = verdict
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] unplotted_reason Object to be assigned
    def unplotted_reason=(unplotted_reason)
      validator = EnumAttributeValidator.new('String', ["no_sport_financials", "no_ranked_result"])
      unless validator.valid?(unplotted_reason)
        fail ArgumentError, "invalid value for \"unplotted_reason\", must be one of #{validator.allowable_values}."
      end
      @unplotted_reason = unplotted_reason
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          sport == o.sport &&
          coach == o.coach &&
          pay == o.pay &&
          result == o.result &&
          verdict == o.verdict &&
          quadrant_point == o.quadrant_point &&
          unplotted_reason == o.unplotted_reason
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [sport, coach, pay, result, verdict, quadrant_point, unplotted_reason].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
