=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.1-dev.10297

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # Provenance of a report built from an ask (04.2 first-open strip)
  class DeskRequestContext < ApiModelBase
    attr_accessor :request_uuid

    attr_accessor :requester_name

    attr_accessor :requested_at

    # The ask's body
    attr_accessor :quote

    # Backend-committed copy (\"delivered in 2 days\")
    attr_accessor :delivered_in_label

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'request_uuid' => :'request_uuid',
        :'requester_name' => :'requester_name',
        :'requested_at' => :'requested_at',
        :'quote' => :'quote',
        :'delivered_in_label' => :'delivered_in_label'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'request_uuid' => :'String',
        :'requester_name' => :'String',
        :'requested_at' => :'Time',
        :'quote' => :'String',
        :'delivered_in_label' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'delivered_in_label'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::DeskRequestContext` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::DeskRequestContext`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'request_uuid')
        self.request_uuid = attributes[:'request_uuid']
      else
        self.request_uuid = nil
      end

      if attributes.key?(:'requester_name')
        self.requester_name = attributes[:'requester_name']
      else
        self.requester_name = nil
      end

      if attributes.key?(:'requested_at')
        self.requested_at = attributes[:'requested_at']
      else
        self.requested_at = nil
      end

      if attributes.key?(:'quote')
        self.quote = attributes[:'quote']
      else
        self.quote = nil
      end

      if attributes.key?(:'delivered_in_label')
        self.delivered_in_label = attributes[:'delivered_in_label']
      else
        self.delivered_in_label = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @request_uuid.nil?
        invalid_properties.push('invalid value for "request_uuid", request_uuid cannot be nil.')
      end

      if @requester_name.nil?
        invalid_properties.push('invalid value for "requester_name", requester_name cannot be nil.')
      end

      if @requested_at.nil?
        invalid_properties.push('invalid value for "requested_at", requested_at cannot be nil.')
      end

      if @quote.nil?
        invalid_properties.push('invalid value for "quote", quote cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @request_uuid.nil?
      return false if @requester_name.nil?
      return false if @requested_at.nil?
      return false if @quote.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] request_uuid Value to be assigned
    def request_uuid=(request_uuid)
      if request_uuid.nil?
        fail ArgumentError, 'request_uuid cannot be nil'
      end

      @request_uuid = request_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] requester_name Value to be assigned
    def requester_name=(requester_name)
      if requester_name.nil?
        fail ArgumentError, 'requester_name cannot be nil'
      end

      @requester_name = requester_name
    end

    # Custom attribute writer method with validation
    # @param [Object] requested_at Value to be assigned
    def requested_at=(requested_at)
      if requested_at.nil?
        fail ArgumentError, 'requested_at cannot be nil'
      end

      @requested_at = requested_at
    end

    # Custom attribute writer method with validation
    # @param [Object] quote Value to be assigned
    def quote=(quote)
      if quote.nil?
        fail ArgumentError, 'quote cannot be nil'
      end

      @quote = quote
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          request_uuid == o.request_uuid &&
          requester_name == o.requester_name &&
          requested_at == o.requested_at &&
          quote == o.quote &&
          delivered_in_label == o.delivered_in_label
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [request_uuid, requester_name, requested_at, quote, delivered_in_label].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
