=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10377

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # One 06.1 queue row (frontend DeskAdminQueueRow, structured facts only)
  class DeskAdminQueueRow < ApiModelBase
    # The report's uuid (kind=report) or the request's (kind=ask)
    attr_accessor :uuid

    attr_accessor :kind

    attr_accessor :status

    attr_accessor :title

    attr_accessor :account

    attr_accessor :requested_by

    attr_accessor :ask_body

    # The customer's 03.1 tile choice; null when none was picked
    attr_accessor :ask_category

    # The reader CTA the ask started from (report-markup.md §8); null for a guided ask
    attr_accessor :cta_key

    # The title of the report that CTA was read on; null with cta_key
    attr_accessor :source_report_title

    attr_accessor :ask_received_at

    # The under-a-day promise's edge, pauses added; new asks only
    attr_accessor :due_at

    attr_accessor :clock_paused

    attr_accessor :has_html

    attr_accessor :artifact_kinds

    attr_accessor :published_at

    attr_accessor :updated_at

    attr_accessor :hidden_at

    attr_accessor :hidden_reason

    # Every reader's opens, summed
    attr_accessor :open_count

    # The row's sort key (newest first)
    attr_accessor :activity_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'kind' => :'kind',
        :'status' => :'status',
        :'title' => :'title',
        :'account' => :'account',
        :'requested_by' => :'requested_by',
        :'ask_body' => :'ask_body',
        :'ask_category' => :'ask_category',
        :'cta_key' => :'cta_key',
        :'source_report_title' => :'source_report_title',
        :'ask_received_at' => :'ask_received_at',
        :'due_at' => :'due_at',
        :'clock_paused' => :'clock_paused',
        :'has_html' => :'has_html',
        :'artifact_kinds' => :'artifact_kinds',
        :'published_at' => :'published_at',
        :'updated_at' => :'updated_at',
        :'hidden_at' => :'hidden_at',
        :'hidden_reason' => :'hidden_reason',
        :'open_count' => :'open_count',
        :'activity_at' => :'activity_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'kind' => :'String',
        :'status' => :'String',
        :'title' => :'String',
        :'account' => :'DeskAdminAccount',
        :'requested_by' => :'String',
        :'ask_body' => :'String',
        :'ask_category' => :'String',
        :'cta_key' => :'String',
        :'source_report_title' => :'String',
        :'ask_received_at' => :'Time',
        :'due_at' => :'Time',
        :'clock_paused' => :'Boolean',
        :'has_html' => :'Boolean',
        :'artifact_kinds' => :'Array<String>',
        :'published_at' => :'Time',
        :'updated_at' => :'Time',
        :'hidden_at' => :'Time',
        :'hidden_reason' => :'String',
        :'open_count' => :'Integer',
        :'activity_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'requested_by',
        :'ask_body',
        :'ask_category',
        :'cta_key',
        :'source_report_title',
        :'ask_received_at',
        :'due_at',
        :'published_at',
        :'updated_at',
        :'hidden_at',
        :'hidden_reason',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::DeskAdminQueueRow` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::DeskAdminQueueRow`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      else
        self.uuid = nil
      end

      if attributes.key?(:'kind')
        self.kind = attributes[:'kind']
      else
        self.kind = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'account')
        self.account = attributes[:'account']
      else
        self.account = nil
      end

      if attributes.key?(:'requested_by')
        self.requested_by = attributes[:'requested_by']
      else
        self.requested_by = nil
      end

      if attributes.key?(:'ask_body')
        self.ask_body = attributes[:'ask_body']
      else
        self.ask_body = nil
      end

      if attributes.key?(:'ask_category')
        self.ask_category = attributes[:'ask_category']
      else
        self.ask_category = nil
      end

      if attributes.key?(:'cta_key')
        self.cta_key = attributes[:'cta_key']
      else
        self.cta_key = nil
      end

      if attributes.key?(:'source_report_title')
        self.source_report_title = attributes[:'source_report_title']
      else
        self.source_report_title = nil
      end

      if attributes.key?(:'ask_received_at')
        self.ask_received_at = attributes[:'ask_received_at']
      else
        self.ask_received_at = nil
      end

      if attributes.key?(:'due_at')
        self.due_at = attributes[:'due_at']
      else
        self.due_at = nil
      end

      if attributes.key?(:'clock_paused')
        self.clock_paused = attributes[:'clock_paused']
      else
        self.clock_paused = nil
      end

      if attributes.key?(:'has_html')
        self.has_html = attributes[:'has_html']
      else
        self.has_html = nil
      end

      if attributes.key?(:'artifact_kinds')
        if (value = attributes[:'artifact_kinds']).is_a?(Array)
          self.artifact_kinds = value
        end
      else
        self.artifact_kinds = nil
      end

      if attributes.key?(:'published_at')
        self.published_at = attributes[:'published_at']
      else
        self.published_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'hidden_at')
        self.hidden_at = attributes[:'hidden_at']
      else
        self.hidden_at = nil
      end

      if attributes.key?(:'hidden_reason')
        self.hidden_reason = attributes[:'hidden_reason']
      else
        self.hidden_reason = nil
      end

      if attributes.key?(:'open_count')
        self.open_count = attributes[:'open_count']
      else
        self.open_count = nil
      end

      if attributes.key?(:'activity_at')
        self.activity_at = attributes[:'activity_at']
      else
        self.activity_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @uuid.nil?
        invalid_properties.push('invalid value for "uuid", uuid cannot be nil.')
      end

      if @kind.nil?
        invalid_properties.push('invalid value for "kind", kind cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @account.nil?
        invalid_properties.push('invalid value for "account", account cannot be nil.')
      end

      if @clock_paused.nil?
        invalid_properties.push('invalid value for "clock_paused", clock_paused cannot be nil.')
      end

      if @has_html.nil?
        invalid_properties.push('invalid value for "has_html", has_html cannot be nil.')
      end

      if @artifact_kinds.nil?
        invalid_properties.push('invalid value for "artifact_kinds", artifact_kinds cannot be nil.')
      end

      if @open_count.nil?
        invalid_properties.push('invalid value for "open_count", open_count cannot be nil.')
      end

      if @activity_at.nil?
        invalid_properties.push('invalid value for "activity_at", activity_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @uuid.nil?
      return false if @kind.nil?
      kind_validator = EnumAttributeValidator.new('String', ["report", "ask"])
      return false unless kind_validator.valid?(@kind)
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["new-ask", "draft", "published", "hidden", "awaiting-client", "closed"])
      return false unless status_validator.valid?(@status)
      return false if @title.nil?
      return false if @account.nil?
      ask_category_validator = EnumAttributeValidator.new('String', ["coaches-staff", "vendors-deals", "money-budgets", "my-peers", "other"])
      return false unless ask_category_validator.valid?(@ask_category)
      cta_key_validator = EnumAttributeValidator.new('String', ["another-sport", "different-peers", "push-on-this", "ask-anything", "make-report", "candidate-list", "extension-raise-scenario", "buyout-schedule", "recruit-position", "retention-raise-case", "staff-benchmark-all-sports", "run-bid-process", "draft-counter", "bid-one-pager", "budget-proposal", "case-for-support", "rerun-on-filing", "board-deck", "defend-line", "track-actuals", "model-termination", "compare-exposure", "peer-buyout-alert", "walk-us-through", "board-version"])
      return false unless cta_key_validator.valid?(@cta_key)
      return false if @clock_paused.nil?
      return false if @has_html.nil?
      return false if @artifact_kinds.nil?
      return false if @open_count.nil?
      return false if @activity_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] uuid Value to be assigned
    def uuid=(uuid)
      if uuid.nil?
        fail ArgumentError, 'uuid cannot be nil'
      end

      @uuid = uuid
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kind Object to be assigned
    def kind=(kind)
      validator = EnumAttributeValidator.new('String', ["report", "ask"])
      unless validator.valid?(kind)
        fail ArgumentError, "invalid value for \"kind\", must be one of #{validator.allowable_values}."
      end
      @kind = kind
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["new-ask", "draft", "published", "hidden", "awaiting-client", "closed"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] account Value to be assigned
    def account=(account)
      if account.nil?
        fail ArgumentError, 'account cannot be nil'
      end

      @account = account
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] ask_category Object to be assigned
    def ask_category=(ask_category)
      validator = EnumAttributeValidator.new('String', ["coaches-staff", "vendors-deals", "money-budgets", "my-peers", "other"])
      unless validator.valid?(ask_category)
        fail ArgumentError, "invalid value for \"ask_category\", must be one of #{validator.allowable_values}."
      end
      @ask_category = ask_category
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cta_key Object to be assigned
    def cta_key=(cta_key)
      validator = EnumAttributeValidator.new('String', ["another-sport", "different-peers", "push-on-this", "ask-anything", "make-report", "candidate-list", "extension-raise-scenario", "buyout-schedule", "recruit-position", "retention-raise-case", "staff-benchmark-all-sports", "run-bid-process", "draft-counter", "bid-one-pager", "budget-proposal", "case-for-support", "rerun-on-filing", "board-deck", "defend-line", "track-actuals", "model-termination", "compare-exposure", "peer-buyout-alert", "walk-us-through", "board-version"])
      unless validator.valid?(cta_key)
        fail ArgumentError, "invalid value for \"cta_key\", must be one of #{validator.allowable_values}."
      end
      @cta_key = cta_key
    end

    # Custom attribute writer method with validation
    # @param [Object] clock_paused Value to be assigned
    def clock_paused=(clock_paused)
      if clock_paused.nil?
        fail ArgumentError, 'clock_paused cannot be nil'
      end

      @clock_paused = clock_paused
    end

    # Custom attribute writer method with validation
    # @param [Object] has_html Value to be assigned
    def has_html=(has_html)
      if has_html.nil?
        fail ArgumentError, 'has_html cannot be nil'
      end

      @has_html = has_html
    end

    # Custom attribute writer method with validation
    # @param [Object] open_count Value to be assigned
    def open_count=(open_count)
      if open_count.nil?
        fail ArgumentError, 'open_count cannot be nil'
      end

      @open_count = open_count
    end

    # Custom attribute writer method with validation
    # @param [Object] activity_at Value to be assigned
    def activity_at=(activity_at)
      if activity_at.nil?
        fail ArgumentError, 'activity_at cannot be nil'
      end

      @activity_at = activity_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uuid == o.uuid &&
          kind == o.kind &&
          status == o.status &&
          title == o.title &&
          account == o.account &&
          requested_by == o.requested_by &&
          ask_body == o.ask_body &&
          ask_category == o.ask_category &&
          cta_key == o.cta_key &&
          source_report_title == o.source_report_title &&
          ask_received_at == o.ask_received_at &&
          due_at == o.due_at &&
          clock_paused == o.clock_paused &&
          has_html == o.has_html &&
          artifact_kinds == o.artifact_kinds &&
          published_at == o.published_at &&
          updated_at == o.updated_at &&
          hidden_at == o.hidden_at &&
          hidden_reason == o.hidden_reason &&
          open_count == o.open_count &&
          activity_at == o.activity_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, kind, status, title, account, requested_by, ask_body, ask_category, cta_key, source_report_title, ask_received_at, due_at, clock_paused, has_html, artifact_kinds, published_at, updated_at, hidden_at, hidden_reason, open_count, activity_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
