=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.8-dev.10620

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class DeskQueueEngagement < ApiModelBase
    attr_accessor :report_uuid

    attr_accessor :status

    attr_accessor :unique_viewers

    attr_accessor :total_opens

    # Latest qualifying customer open in the effective interval, across every viewer/version; null at zero.
    attr_accessor :last_viewed_at

    attr_accessor :refreshed_at

    attr_accessor :period

    attr_accessor :coverage

    attr_accessor :error

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'report_uuid' => :'report_uuid',
        :'status' => :'status',
        :'unique_viewers' => :'unique_viewers',
        :'total_opens' => :'total_opens',
        :'last_viewed_at' => :'last_viewed_at',
        :'refreshed_at' => :'refreshed_at',
        :'period' => :'period',
        :'coverage' => :'coverage',
        :'error' => :'error'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'report_uuid' => :'String',
        :'status' => :'String',
        :'unique_viewers' => :'Integer',
        :'total_opens' => :'Integer',
        :'last_viewed_at' => :'Time',
        :'refreshed_at' => :'Time',
        :'period' => :'DeskQueueEngagementPeriod',
        :'coverage' => :'DeskQueueEngagementCoverage',
        :'error' => :'DeskQueueEngagementError'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'unique_viewers',
        :'total_opens',
        :'last_viewed_at',
        :'refreshed_at',
        :'error'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::DeskQueueEngagement` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::DeskQueueEngagement`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'report_uuid')
        self.report_uuid = attributes[:'report_uuid']
      else
        self.report_uuid = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'unique_viewers')
        self.unique_viewers = attributes[:'unique_viewers']
      else
        self.unique_viewers = nil
      end

      if attributes.key?(:'total_opens')
        self.total_opens = attributes[:'total_opens']
      else
        self.total_opens = nil
      end

      if attributes.key?(:'last_viewed_at')
        self.last_viewed_at = attributes[:'last_viewed_at']
      else
        self.last_viewed_at = nil
      end

      if attributes.key?(:'refreshed_at')
        self.refreshed_at = attributes[:'refreshed_at']
      else
        self.refreshed_at = nil
      end

      if attributes.key?(:'period')
        self.period = attributes[:'period']
      else
        self.period = nil
      end

      if attributes.key?(:'coverage')
        self.coverage = attributes[:'coverage']
      else
        self.coverage = nil
      end

      if attributes.key?(:'error')
        self.error = attributes[:'error']
      else
        self.error = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @report_uuid.nil?
        invalid_properties.push('invalid value for "report_uuid", report_uuid cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @unique_viewers > 9007199254740991
        invalid_properties.push('invalid value for "unique_viewers", must be smaller than or equal to 9007199254740991.')
      end

      if @unique_viewers < 0
        invalid_properties.push('invalid value for "unique_viewers", must be greater than or equal to 0.')
      end

      if @total_opens > 9007199254740991
        invalid_properties.push('invalid value for "total_opens", must be smaller than or equal to 9007199254740991.')
      end

      if @total_opens < 0
        invalid_properties.push('invalid value for "total_opens", must be greater than or equal to 0.')
      end

      if @period.nil?
        invalid_properties.push('invalid value for "period", period cannot be nil.')
      end

      if @coverage.nil?
        invalid_properties.push('invalid value for "coverage", coverage cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @report_uuid.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["available", "partial", "unavailable", "not_published", "not_found"])
      return false unless status_validator.valid?(@status)
      return false if @unique_viewers > 9007199254740991
      return false if @unique_viewers < 0
      return false if @total_opens > 9007199254740991
      return false if @total_opens < 0
      return false if @period.nil?
      return false if @coverage.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] report_uuid Value to be assigned
    def report_uuid=(report_uuid)
      if report_uuid.nil?
        fail ArgumentError, 'report_uuid cannot be nil'
      end

      @report_uuid = report_uuid
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["available", "partial", "unavailable", "not_published", "not_found"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] unique_viewers Value to be assigned
    def unique_viewers=(unique_viewers)
      if !unique_viewers.nil? && unique_viewers > 9007199254740991
        fail ArgumentError, 'invalid value for "unique_viewers", must be smaller than or equal to 9007199254740991.'
      end

      if !unique_viewers.nil? && unique_viewers < 0
        fail ArgumentError, 'invalid value for "unique_viewers", must be greater than or equal to 0.'
      end

      @unique_viewers = unique_viewers
    end

    # Custom attribute writer method with validation
    # @param [Object] total_opens Value to be assigned
    def total_opens=(total_opens)
      if !total_opens.nil? && total_opens > 9007199254740991
        fail ArgumentError, 'invalid value for "total_opens", must be smaller than or equal to 9007199254740991.'
      end

      if !total_opens.nil? && total_opens < 0
        fail ArgumentError, 'invalid value for "total_opens", must be greater than or equal to 0.'
      end

      @total_opens = total_opens
    end

    # Custom attribute writer method with validation
    # @param [Object] period Value to be assigned
    def period=(period)
      if period.nil?
        fail ArgumentError, 'period cannot be nil'
      end

      @period = period
    end

    # Custom attribute writer method with validation
    # @param [Object] coverage Value to be assigned
    def coverage=(coverage)
      if coverage.nil?
        fail ArgumentError, 'coverage cannot be nil'
      end

      @coverage = coverage
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          report_uuid == o.report_uuid &&
          status == o.status &&
          unique_viewers == o.unique_viewers &&
          total_opens == o.total_opens &&
          last_viewed_at == o.last_viewed_at &&
          refreshed_at == o.refreshed_at &&
          period == o.period &&
          coverage == o.coverage &&
          error == o.error
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [report_uuid, status, unique_viewers, total_opens, last_viewed_at, refreshed_at, period, coverage, error].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
