=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10377

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class EadaDerivedMetric < ApiModelBase
    attr_accessor :canonical_metric_id

    attr_accessor :label

    attr_accessor :description

    attr_accessor :formula

    attr_accessor :source_service

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'canonical_metric_id' => :'canonical_metric_id',
        :'label' => :'label',
        :'description' => :'description',
        :'formula' => :'formula',
        :'source_service' => :'source_service'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'canonical_metric_id' => :'String',
        :'label' => :'String',
        :'description' => :'String',
        :'formula' => :'String',
        :'source_service' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::EadaDerivedMetric` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::EadaDerivedMetric`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'canonical_metric_id')
        self.canonical_metric_id = attributes[:'canonical_metric_id']
      else
        self.canonical_metric_id = nil
      end

      if attributes.key?(:'label')
        self.label = attributes[:'label']
      else
        self.label = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'formula')
        self.formula = attributes[:'formula']
      else
        self.formula = nil
      end

      if attributes.key?(:'source_service')
        self.source_service = attributes[:'source_service']
      else
        self.source_service = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @canonical_metric_id.nil?
        invalid_properties.push('invalid value for "canonical_metric_id", canonical_metric_id cannot be nil.')
      end

      if @label.nil?
        invalid_properties.push('invalid value for "label", label cannot be nil.')
      end

      if @formula.nil?
        invalid_properties.push('invalid value for "formula", formula cannot be nil.')
      end

      if @source_service.nil?
        invalid_properties.push('invalid value for "source_service", source_service cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @canonical_metric_id.nil?
      return false if @label.nil?
      return false if @formula.nil?
      return false if @source_service.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] canonical_metric_id Value to be assigned
    def canonical_metric_id=(canonical_metric_id)
      if canonical_metric_id.nil?
        fail ArgumentError, 'canonical_metric_id cannot be nil'
      end

      @canonical_metric_id = canonical_metric_id
    end

    # Custom attribute writer method with validation
    # @param [Object] label Value to be assigned
    def label=(label)
      if label.nil?
        fail ArgumentError, 'label cannot be nil'
      end

      @label = label
    end

    # Custom attribute writer method with validation
    # @param [Object] formula Value to be assigned
    def formula=(formula)
      if formula.nil?
        fail ArgumentError, 'formula cannot be nil'
      end

      @formula = formula
    end

    # Custom attribute writer method with validation
    # @param [Object] source_service Value to be assigned
    def source_service=(source_service)
      if source_service.nil?
        fail ArgumentError, 'source_service cannot be nil'
      end

      @source_service = source_service
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          canonical_metric_id == o.canonical_metric_id &&
          label == o.label &&
          description == o.description &&
          formula == o.formula &&
          source_service == o.source_service
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [canonical_metric_id, label, description, formula, source_service].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
