=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10377

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class FinancialComparisonRankedRow < ApiModelBase
    attr_accessor :rank

    attr_accessor :school_id

    attr_accessor :school_name

    attr_accessor :source

    attr_accessor :year

    attr_accessor :fallback_reason

    # The metric's raw typed value for this school/source
    attr_accessor :value

    attr_accessor :comparability_state

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'rank' => :'rank',
        :'school_id' => :'school_id',
        :'school_name' => :'school_name',
        :'source' => :'source',
        :'year' => :'year',
        :'fallback_reason' => :'fallback_reason',
        :'value' => :'value',
        :'comparability_state' => :'comparability_state'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'rank' => :'Integer',
        :'school_id' => :'Integer',
        :'school_name' => :'String',
        :'source' => :'String',
        :'year' => :'Integer',
        :'fallback_reason' => :'String',
        :'value' => :'Object',
        :'comparability_state' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'year',
        :'fallback_reason',
        :'value',
        :'comparability_state'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::FinancialComparisonRankedRow` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::FinancialComparisonRankedRow`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'rank')
        self.rank = attributes[:'rank']
      else
        self.rank = nil
      end

      if attributes.key?(:'school_id')
        self.school_id = attributes[:'school_id']
      else
        self.school_id = nil
      end

      if attributes.key?(:'school_name')
        self.school_name = attributes[:'school_name']
      else
        self.school_name = nil
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      else
        self.source = nil
      end

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      end

      if attributes.key?(:'fallback_reason')
        self.fallback_reason = attributes[:'fallback_reason']
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      else
        self.value = nil
      end

      if attributes.key?(:'comparability_state')
        self.comparability_state = attributes[:'comparability_state']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @rank.nil?
        invalid_properties.push('invalid value for "rank", rank cannot be nil.')
      end

      if @school_id.nil?
        invalid_properties.push('invalid value for "school_id", school_id cannot be nil.')
      end

      if @school_name.nil?
        invalid_properties.push('invalid value for "school_name", school_name cannot be nil.')
      end

      if @source.nil?
        invalid_properties.push('invalid value for "source", source cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @rank.nil?
      return false if @school_id.nil?
      return false if @school_name.nil?
      return false if @source.nil?
      source_validator = EnumAttributeValidator.new('String', ["eada", "ncaa_frs"])
      return false unless source_validator.valid?(@source)
      comparability_state_validator = EnumAttributeValidator.new('String', ["mergeable", "comparison_only", "not_comparable", "source_only"])
      return false unless comparability_state_validator.valid?(@comparability_state)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] rank Value to be assigned
    def rank=(rank)
      if rank.nil?
        fail ArgumentError, 'rank cannot be nil'
      end

      @rank = rank
    end

    # Custom attribute writer method with validation
    # @param [Object] school_id Value to be assigned
    def school_id=(school_id)
      if school_id.nil?
        fail ArgumentError, 'school_id cannot be nil'
      end

      @school_id = school_id
    end

    # Custom attribute writer method with validation
    # @param [Object] school_name Value to be assigned
    def school_name=(school_name)
      if school_name.nil?
        fail ArgumentError, 'school_name cannot be nil'
      end

      @school_name = school_name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] source Object to be assigned
    def source=(source)
      validator = EnumAttributeValidator.new('String', ["eada", "ncaa_frs"])
      unless validator.valid?(source)
        fail ArgumentError, "invalid value for \"source\", must be one of #{validator.allowable_values}."
      end
      @source = source
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] comparability_state Object to be assigned
    def comparability_state=(comparability_state)
      validator = EnumAttributeValidator.new('String', ["mergeable", "comparison_only", "not_comparable", "source_only"])
      unless validator.valid?(comparability_state)
        fail ArgumentError, "invalid value for \"comparability_state\", must be one of #{validator.allowable_values}."
      end
      @comparability_state = comparability_state
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          rank == o.rank &&
          school_id == o.school_id &&
          school_name == o.school_name &&
          source == o.source &&
          year == o.year &&
          fallback_reason == o.fallback_reason &&
          value == o.value &&
          comparability_state == o.comparability_state
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [rank, school_id, school_name, source, year, fallback_reason, value, comparability_state].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
