=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10377

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # Only present when metric was given. blended_ranking combines every source's values into one ranked list, but only when Financials::Comparability marks this canonical metric catalog-approved (comparability_state mergeable) for cross-source blending — no dollar-valued metric is mergeable in the catalog today, so blended_ranking is null with a blended_reason for every current financial metric. ranking_by_source is always populated — one ranking per source, kept visibly separate.
  class FinancialComparison < ApiModelBase
    attr_accessor :metric

    attr_accessor :mergeable_across_sources

    attr_accessor :blended_ranking

    # Present only when blended_ranking is null — why this metric was not blended across sources.
    attr_accessor :blended_reason

    # One key per source that produced at least one matching row (e.g. eada, ncaa_frs), each an array of ranked rows for that source alone.
    attr_accessor :ranking_by_source

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'metric' => :'metric',
        :'mergeable_across_sources' => :'mergeable_across_sources',
        :'blended_ranking' => :'blended_ranking',
        :'blended_reason' => :'blended_reason',
        :'ranking_by_source' => :'ranking_by_source'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'metric' => :'String',
        :'mergeable_across_sources' => :'Boolean',
        :'blended_ranking' => :'Array<FinancialComparisonRankedRow>',
        :'blended_reason' => :'String',
        :'ranking_by_source' => :'Hash<String, Array<FinancialComparisonRankedRow>>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'blended_ranking',
        :'blended_reason',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::FinancialComparison` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::FinancialComparison`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'metric')
        self.metric = attributes[:'metric']
      else
        self.metric = nil
      end

      if attributes.key?(:'mergeable_across_sources')
        self.mergeable_across_sources = attributes[:'mergeable_across_sources']
      else
        self.mergeable_across_sources = nil
      end

      if attributes.key?(:'blended_ranking')
        if (value = attributes[:'blended_ranking']).is_a?(Array)
          self.blended_ranking = value
        end
      end

      if attributes.key?(:'blended_reason')
        self.blended_reason = attributes[:'blended_reason']
      end

      if attributes.key?(:'ranking_by_source')
        if (value = attributes[:'ranking_by_source']).is_a?(Hash)
          self.ranking_by_source = value
        end
      else
        self.ranking_by_source = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @metric.nil?
        invalid_properties.push('invalid value for "metric", metric cannot be nil.')
      end

      if @mergeable_across_sources.nil?
        invalid_properties.push('invalid value for "mergeable_across_sources", mergeable_across_sources cannot be nil.')
      end

      if @ranking_by_source.nil?
        invalid_properties.push('invalid value for "ranking_by_source", ranking_by_source cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @metric.nil?
      return false if @mergeable_across_sources.nil?
      return false if @ranking_by_source.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] metric Value to be assigned
    def metric=(metric)
      if metric.nil?
        fail ArgumentError, 'metric cannot be nil'
      end

      @metric = metric
    end

    # Custom attribute writer method with validation
    # @param [Object] mergeable_across_sources Value to be assigned
    def mergeable_across_sources=(mergeable_across_sources)
      if mergeable_across_sources.nil?
        fail ArgumentError, 'mergeable_across_sources cannot be nil'
      end

      @mergeable_across_sources = mergeable_across_sources
    end

    # Custom attribute writer method with validation
    # @param [Object] ranking_by_source Value to be assigned
    def ranking_by_source=(ranking_by_source)
      if ranking_by_source.nil?
        fail ArgumentError, 'ranking_by_source cannot be nil'
      end

      @ranking_by_source = ranking_by_source
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          metric == o.metric &&
          mergeable_across_sources == o.mergeable_across_sources &&
          blended_ranking == o.blended_ranking &&
          blended_reason == o.blended_reason &&
          ranking_by_source == o.ranking_by_source
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [metric, mergeable_across_sources, blended_ranking, blended_reason, ranking_by_source].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
