=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.62

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class FoiaInboxExpectedCompensation < ApiModelBase
    attr_accessor :year

    attr_accessor :school_id

    attr_accessor :coach_id

    attr_accessor :contract_status

    attr_accessor :comment

    attr_accessor :updated_at

    attr_accessor :positions_sha256

    attr_accessor :positions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'year' => :'year',
        :'school_id' => :'school_id',
        :'coach_id' => :'coach_id',
        :'contract_status' => :'contract_status',
        :'comment' => :'comment',
        :'updated_at' => :'updated_at',
        :'positions_sha256' => :'positions_sha256',
        :'positions' => :'positions'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'year' => :'Integer',
        :'school_id' => :'Integer',
        :'coach_id' => :'Integer',
        :'contract_status' => :'String',
        :'comment' => :'String',
        :'updated_at' => :'Time',
        :'positions_sha256' => :'String',
        :'positions' => :'Array<FoiaInboxExpectedPosition>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'contract_status',
        :'comment',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::FoiaInboxExpectedCompensation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::FoiaInboxExpectedCompensation`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      else
        self.year = nil
      end

      if attributes.key?(:'school_id')
        self.school_id = attributes[:'school_id']
      else
        self.school_id = nil
      end

      if attributes.key?(:'coach_id')
        self.coach_id = attributes[:'coach_id']
      else
        self.coach_id = nil
      end

      if attributes.key?(:'contract_status')
        self.contract_status = attributes[:'contract_status']
      else
        self.contract_status = nil
      end

      if attributes.key?(:'comment')
        self.comment = attributes[:'comment']
      else
        self.comment = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'positions_sha256')
        self.positions_sha256 = attributes[:'positions_sha256']
      else
        self.positions_sha256 = nil
      end

      if attributes.key?(:'positions')
        if (value = attributes[:'positions']).is_a?(Array)
          self.positions = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @year.nil?
        invalid_properties.push('invalid value for "year", year cannot be nil.')
      end

      if @school_id.nil?
        invalid_properties.push('invalid value for "school_id", school_id cannot be nil.')
      end

      if @coach_id.nil?
        invalid_properties.push('invalid value for "coach_id", coach_id cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @positions_sha256.nil?
        invalid_properties.push('invalid value for "positions_sha256", positions_sha256 cannot be nil.')
      end

      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @positions_sha256 !~ pattern
        invalid_properties.push("invalid value for \"positions_sha256\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @year.nil?
      return false if @school_id.nil?
      return false if @coach_id.nil?
      return false if @updated_at.nil?
      return false if @positions_sha256.nil?
      return false if @positions_sha256 !~ Regexp.new(/^[a-f0-9]{64}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] year Value to be assigned
    def year=(year)
      if year.nil?
        fail ArgumentError, 'year cannot be nil'
      end

      @year = year
    end

    # Custom attribute writer method with validation
    # @param [Object] school_id Value to be assigned
    def school_id=(school_id)
      if school_id.nil?
        fail ArgumentError, 'school_id cannot be nil'
      end

      @school_id = school_id
    end

    # Custom attribute writer method with validation
    # @param [Object] coach_id Value to be assigned
    def coach_id=(coach_id)
      if coach_id.nil?
        fail ArgumentError, 'coach_id cannot be nil'
      end

      @coach_id = coach_id
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] positions_sha256 Value to be assigned
    def positions_sha256=(positions_sha256)
      if positions_sha256.nil?
        fail ArgumentError, 'positions_sha256 cannot be nil'
      end

      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if positions_sha256 !~ pattern
        fail ArgumentError, "invalid value for \"positions_sha256\", must conform to the pattern #{pattern}."
      end

      @positions_sha256 = positions_sha256
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          year == o.year &&
          school_id == o.school_id &&
          coach_id == o.coach_id &&
          contract_status == o.contract_status &&
          comment == o.comment &&
          updated_at == o.updated_at &&
          positions_sha256 == o.positions_sha256 &&
          positions == o.positions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [year, school_id, coach_id, contract_status, comment, updated_at, positions_sha256, positions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
