=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.34-dev.9866

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class FoiaFollowUpRecentReceivedItem < ApiModelBase
    attr_accessor :requested_item_id

    attr_accessor :requestable_type

    attr_accessor :requestable_id

    attr_accessor :requestable_data

    attr_accessor :title

    attr_accessor :status

    attr_accessor :status_changed_at

    attr_accessor :received_at

    attr_accessor :previous_status

    attr_accessor :coach_id

    attr_accessor :coach_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'requested_item_id' => :'requested_item_id',
        :'requestable_type' => :'requestable_type',
        :'requestable_id' => :'requestable_id',
        :'requestable_data' => :'requestable_data',
        :'title' => :'title',
        :'status' => :'status',
        :'status_changed_at' => :'status_changed_at',
        :'received_at' => :'received_at',
        :'previous_status' => :'previous_status',
        :'coach_id' => :'coach_id',
        :'coach_name' => :'coach_name'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'requested_item_id' => :'Integer',
        :'requestable_type' => :'String',
        :'requestable_id' => :'Integer',
        :'requestable_data' => :'FoiaFollowUpRequestableData',
        :'title' => :'String',
        :'status' => :'String',
        :'status_changed_at' => :'Time',
        :'received_at' => :'Time',
        :'previous_status' => :'String',
        :'coach_id' => :'Integer',
        :'coach_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'requestable_type',
        :'requestable_id',
        :'status_changed_at',
        :'received_at',
        :'previous_status',
        :'coach_id',
        :'coach_name'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::FoiaFollowUpRecentReceivedItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::FoiaFollowUpRecentReceivedItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'requested_item_id')
        self.requested_item_id = attributes[:'requested_item_id']
      end

      if attributes.key?(:'requestable_type')
        self.requestable_type = attributes[:'requestable_type']
      end

      if attributes.key?(:'requestable_id')
        self.requestable_id = attributes[:'requestable_id']
      end

      if attributes.key?(:'requestable_data')
        self.requestable_data = attributes[:'requestable_data']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'status_changed_at')
        self.status_changed_at = attributes[:'status_changed_at']
      end

      if attributes.key?(:'received_at')
        self.received_at = attributes[:'received_at']
      end

      if attributes.key?(:'previous_status')
        self.previous_status = attributes[:'previous_status']
      end

      if attributes.key?(:'coach_id')
        self.coach_id = attributes[:'coach_id']
      end

      if attributes.key?(:'coach_name')
        self.coach_name = attributes[:'coach_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          requested_item_id == o.requested_item_id &&
          requestable_type == o.requestable_type &&
          requestable_id == o.requestable_id &&
          requestable_data == o.requestable_data &&
          title == o.title &&
          status == o.status &&
          status_changed_at == o.status_changed_at &&
          received_at == o.received_at &&
          previous_status == o.previous_status &&
          coach_id == o.coach_id &&
          coach_name == o.coach_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [requested_item_id, requestable_type, requestable_id, requestable_data, title, status, status_changed_at, received_at, previous_status, coach_id, coach_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
