=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.9

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class FoiaStatusSummaryMeta < ApiModelBase
    # America/New_York calendar date used for every comparison on every page; must be identical across pages of one collection. Overdue is strictly before this date; follow-up due is on or before it.
    attr_accessor :as_of_date

    # RFC 3339 UTC timestamp regenerated per page (with UTC 'Z' offset); may differ between pages.
    attr_accessor :generated_at

    # IANA name of the business time zone used for as_of_date (America/New_York).
    attr_accessor :timezone

    attr_accessor :filters_applied

    attr_accessor :current_page

    # Effective page size after capping the requested value to 200.
    attr_accessor :per_page

    attr_accessor :max_per_page

    attr_accessor :total_pages

    attr_accessor :total_entries

    attr_accessor :next_page

    attr_accessor :previous_page

    attr_accessor :active_hold_note_prefix

    attr_accessor :active_hold_reasons

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'as_of_date' => :'as_of_date',
        :'generated_at' => :'generated_at',
        :'timezone' => :'timezone',
        :'filters_applied' => :'filters_applied',
        :'current_page' => :'current_page',
        :'per_page' => :'per_page',
        :'max_per_page' => :'max_per_page',
        :'total_pages' => :'total_pages',
        :'total_entries' => :'total_entries',
        :'next_page' => :'next_page',
        :'previous_page' => :'previous_page',
        :'active_hold_note_prefix' => :'active_hold_note_prefix',
        :'active_hold_reasons' => :'active_hold_reasons'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'as_of_date' => :'Date',
        :'generated_at' => :'Time',
        :'timezone' => :'String',
        :'filters_applied' => :'FoiaStatusSummaryFilters',
        :'current_page' => :'Integer',
        :'per_page' => :'Integer',
        :'max_per_page' => :'Integer',
        :'total_pages' => :'Integer',
        :'total_entries' => :'Integer',
        :'next_page' => :'Integer',
        :'previous_page' => :'Integer',
        :'active_hold_note_prefix' => :'String',
        :'active_hold_reasons' => :'Hash<String, String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'next_page',
        :'previous_page',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::FoiaStatusSummaryMeta` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::FoiaStatusSummaryMeta`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'as_of_date')
        self.as_of_date = attributes[:'as_of_date']
      else
        self.as_of_date = nil
      end

      if attributes.key?(:'generated_at')
        self.generated_at = attributes[:'generated_at']
      else
        self.generated_at = nil
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      else
        self.timezone = nil
      end

      if attributes.key?(:'filters_applied')
        self.filters_applied = attributes[:'filters_applied']
      else
        self.filters_applied = nil
      end

      if attributes.key?(:'current_page')
        self.current_page = attributes[:'current_page']
      else
        self.current_page = nil
      end

      if attributes.key?(:'per_page')
        self.per_page = attributes[:'per_page']
      else
        self.per_page = nil
      end

      if attributes.key?(:'max_per_page')
        self.max_per_page = attributes[:'max_per_page']
      else
        self.max_per_page = nil
      end

      if attributes.key?(:'total_pages')
        self.total_pages = attributes[:'total_pages']
      else
        self.total_pages = nil
      end

      if attributes.key?(:'total_entries')
        self.total_entries = attributes[:'total_entries']
      else
        self.total_entries = nil
      end

      if attributes.key?(:'next_page')
        self.next_page = attributes[:'next_page']
      else
        self.next_page = nil
      end

      if attributes.key?(:'previous_page')
        self.previous_page = attributes[:'previous_page']
      else
        self.previous_page = nil
      end

      if attributes.key?(:'active_hold_note_prefix')
        self.active_hold_note_prefix = attributes[:'active_hold_note_prefix']
      else
        self.active_hold_note_prefix = nil
      end

      if attributes.key?(:'active_hold_reasons')
        if (value = attributes[:'active_hold_reasons']).is_a?(Hash)
          self.active_hold_reasons = value
        end
      else
        self.active_hold_reasons = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @as_of_date.nil?
        invalid_properties.push('invalid value for "as_of_date", as_of_date cannot be nil.')
      end

      if @generated_at.nil?
        invalid_properties.push('invalid value for "generated_at", generated_at cannot be nil.')
      end

      if @timezone.nil?
        invalid_properties.push('invalid value for "timezone", timezone cannot be nil.')
      end

      if @filters_applied.nil?
        invalid_properties.push('invalid value for "filters_applied", filters_applied cannot be nil.')
      end

      if @current_page.nil?
        invalid_properties.push('invalid value for "current_page", current_page cannot be nil.')
      end

      if @per_page.nil?
        invalid_properties.push('invalid value for "per_page", per_page cannot be nil.')
      end

      if @max_per_page.nil?
        invalid_properties.push('invalid value for "max_per_page", max_per_page cannot be nil.')
      end

      if @total_pages.nil?
        invalid_properties.push('invalid value for "total_pages", total_pages cannot be nil.')
      end

      if @total_entries.nil?
        invalid_properties.push('invalid value for "total_entries", total_entries cannot be nil.')
      end

      if @active_hold_note_prefix.nil?
        invalid_properties.push('invalid value for "active_hold_note_prefix", active_hold_note_prefix cannot be nil.')
      end

      if @active_hold_reasons.nil?
        invalid_properties.push('invalid value for "active_hold_reasons", active_hold_reasons cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @as_of_date.nil?
      return false if @generated_at.nil?
      return false if @timezone.nil?
      return false if @filters_applied.nil?
      return false if @current_page.nil?
      return false if @per_page.nil?
      return false if @max_per_page.nil?
      return false if @total_pages.nil?
      return false if @total_entries.nil?
      return false if @active_hold_note_prefix.nil?
      return false if @active_hold_reasons.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] as_of_date Value to be assigned
    def as_of_date=(as_of_date)
      if as_of_date.nil?
        fail ArgumentError, 'as_of_date cannot be nil'
      end

      @as_of_date = as_of_date
    end

    # Custom attribute writer method with validation
    # @param [Object] generated_at Value to be assigned
    def generated_at=(generated_at)
      if generated_at.nil?
        fail ArgumentError, 'generated_at cannot be nil'
      end

      @generated_at = generated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] timezone Value to be assigned
    def timezone=(timezone)
      if timezone.nil?
        fail ArgumentError, 'timezone cannot be nil'
      end

      @timezone = timezone
    end

    # Custom attribute writer method with validation
    # @param [Object] filters_applied Value to be assigned
    def filters_applied=(filters_applied)
      if filters_applied.nil?
        fail ArgumentError, 'filters_applied cannot be nil'
      end

      @filters_applied = filters_applied
    end

    # Custom attribute writer method with validation
    # @param [Object] current_page Value to be assigned
    def current_page=(current_page)
      if current_page.nil?
        fail ArgumentError, 'current_page cannot be nil'
      end

      @current_page = current_page
    end

    # Custom attribute writer method with validation
    # @param [Object] per_page Value to be assigned
    def per_page=(per_page)
      if per_page.nil?
        fail ArgumentError, 'per_page cannot be nil'
      end

      @per_page = per_page
    end

    # Custom attribute writer method with validation
    # @param [Object] max_per_page Value to be assigned
    def max_per_page=(max_per_page)
      if max_per_page.nil?
        fail ArgumentError, 'max_per_page cannot be nil'
      end

      @max_per_page = max_per_page
    end

    # Custom attribute writer method with validation
    # @param [Object] total_pages Value to be assigned
    def total_pages=(total_pages)
      if total_pages.nil?
        fail ArgumentError, 'total_pages cannot be nil'
      end

      @total_pages = total_pages
    end

    # Custom attribute writer method with validation
    # @param [Object] total_entries Value to be assigned
    def total_entries=(total_entries)
      if total_entries.nil?
        fail ArgumentError, 'total_entries cannot be nil'
      end

      @total_entries = total_entries
    end

    # Custom attribute writer method with validation
    # @param [Object] active_hold_note_prefix Value to be assigned
    def active_hold_note_prefix=(active_hold_note_prefix)
      if active_hold_note_prefix.nil?
        fail ArgumentError, 'active_hold_note_prefix cannot be nil'
      end

      @active_hold_note_prefix = active_hold_note_prefix
    end

    # Custom attribute writer method with validation
    # @param [Object] active_hold_reasons Value to be assigned
    def active_hold_reasons=(active_hold_reasons)
      if active_hold_reasons.nil?
        fail ArgumentError, 'active_hold_reasons cannot be nil'
      end

      @active_hold_reasons = active_hold_reasons
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          as_of_date == o.as_of_date &&
          generated_at == o.generated_at &&
          timezone == o.timezone &&
          filters_applied == o.filters_applied &&
          current_page == o.current_page &&
          per_page == o.per_page &&
          max_per_page == o.max_per_page &&
          total_pages == o.total_pages &&
          total_entries == o.total_entries &&
          next_page == o.next_page &&
          previous_page == o.previous_page &&
          active_hold_note_prefix == o.active_hold_note_prefix &&
          active_hold_reasons == o.active_hold_reasons
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [as_of_date, generated_at, timezone, filters_applied, current_page, per_page, max_per_page, total_pages, total_entries, next_page, previous_page, active_hold_note_prefix, active_hold_reasons].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
