=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10297

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class HumanOverrideRequestJobPost < ApiModelBase
    attr_accessor :human_override_is_athletics

    # Optional fingerprint of the source snapshot used for the human decision.
    attr_accessor :expected_source_fingerprint

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'human_override_is_athletics' => :'human_override_is_athletics',
        :'expected_source_fingerprint' => :'expected_source_fingerprint'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'human_override_is_athletics' => :'Boolean',
        :'expected_source_fingerprint' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::HumanOverrideRequestJobPost` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::HumanOverrideRequestJobPost`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'human_override_is_athletics')
        self.human_override_is_athletics = attributes[:'human_override_is_athletics']
      else
        self.human_override_is_athletics = nil
      end

      if attributes.key?(:'expected_source_fingerprint')
        self.expected_source_fingerprint = attributes[:'expected_source_fingerprint']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @human_override_is_athletics.nil?
        invalid_properties.push('invalid value for "human_override_is_athletics", human_override_is_athletics cannot be nil.')
      end

      pattern = Regexp.new(/^[0-9a-f]{64}$/)
      if !@expected_source_fingerprint.nil? && @expected_source_fingerprint !~ pattern
        invalid_properties.push("invalid value for \"expected_source_fingerprint\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @human_override_is_athletics.nil?
      return false if !@expected_source_fingerprint.nil? && @expected_source_fingerprint !~ Regexp.new(/^[0-9a-f]{64}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] human_override_is_athletics Value to be assigned
    def human_override_is_athletics=(human_override_is_athletics)
      if human_override_is_athletics.nil?
        fail ArgumentError, 'human_override_is_athletics cannot be nil'
      end

      @human_override_is_athletics = human_override_is_athletics
    end

    # Custom attribute writer method with validation
    # @param [Object] expected_source_fingerprint Value to be assigned
    def expected_source_fingerprint=(expected_source_fingerprint)
      if expected_source_fingerprint.nil?
        fail ArgumentError, 'expected_source_fingerprint cannot be nil'
      end

      pattern = Regexp.new(/^[0-9a-f]{64}$/)
      if expected_source_fingerprint !~ pattern
        fail ArgumentError, "invalid value for \"expected_source_fingerprint\", must conform to the pattern #{pattern}."
      end

      @expected_source_fingerprint = expected_source_fingerprint
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          human_override_is_athletics == o.human_override_is_athletics &&
          expected_source_fingerprint == o.expected_source_fingerprint
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [human_override_is_athletics, expected_source_fingerprint].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
