=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.0-dev.10377

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class NeedsInfoAdminDeskRequest200ResponseData < ApiModelBase
    attr_accessor :uuid

    attr_accessor :status

    attr_accessor :client_note

    attr_accessor :clock_paused

    # The addresses the follow-up was queued for; empty means nothing was sent (no reachable asker, or the delivery could not be queued). The pause is applied either way. 
    attr_accessor :sent_to

    attr_accessor :sent_to_count

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'status' => :'status',
        :'client_note' => :'client_note',
        :'clock_paused' => :'clock_paused',
        :'sent_to' => :'sent_to',
        :'sent_to_count' => :'sent_to_count'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'status' => :'String',
        :'client_note' => :'String',
        :'clock_paused' => :'Boolean',
        :'sent_to' => :'Array<String>',
        :'sent_to_count' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'client_note',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::NeedsInfoAdminDeskRequest200ResponseData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::NeedsInfoAdminDeskRequest200ResponseData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      else
        self.uuid = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'client_note')
        self.client_note = attributes[:'client_note']
      else
        self.client_note = nil
      end

      if attributes.key?(:'clock_paused')
        self.clock_paused = attributes[:'clock_paused']
      else
        self.clock_paused = nil
      end

      if attributes.key?(:'sent_to')
        if (value = attributes[:'sent_to']).is_a?(Array)
          self.sent_to = value
        end
      else
        self.sent_to = nil
      end

      if attributes.key?(:'sent_to_count')
        self.sent_to_count = attributes[:'sent_to_count']
      else
        self.sent_to_count = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @uuid.nil?
        invalid_properties.push('invalid value for "uuid", uuid cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @clock_paused.nil?
        invalid_properties.push('invalid value for "clock_paused", clock_paused cannot be nil.')
      end

      if @sent_to.nil?
        invalid_properties.push('invalid value for "sent_to", sent_to cannot be nil.')
      end

      if @sent_to_count.nil?
        invalid_properties.push('invalid value for "sent_to_count", sent_to_count cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @uuid.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["awaiting_client"])
      return false unless status_validator.valid?(@status)
      return false if @clock_paused.nil?
      return false if @sent_to.nil?
      return false if @sent_to_count.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] uuid Value to be assigned
    def uuid=(uuid)
      if uuid.nil?
        fail ArgumentError, 'uuid cannot be nil'
      end

      @uuid = uuid
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["awaiting_client"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] clock_paused Value to be assigned
    def clock_paused=(clock_paused)
      if clock_paused.nil?
        fail ArgumentError, 'clock_paused cannot be nil'
      end

      @clock_paused = clock_paused
    end

    # Custom attribute writer method with validation
    # @param [Object] sent_to Value to be assigned
    def sent_to=(sent_to)
      if sent_to.nil?
        fail ArgumentError, 'sent_to cannot be nil'
      end

      @sent_to = sent_to
    end

    # Custom attribute writer method with validation
    # @param [Object] sent_to_count Value to be assigned
    def sent_to_count=(sent_to_count)
      if sent_to_count.nil?
        fail ArgumentError, 'sent_to_count cannot be nil'
      end

      @sent_to_count = sent_to_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uuid == o.uuid &&
          status == o.status &&
          client_note == o.client_note &&
          clock_paused == o.clock_paused &&
          sent_to == o.sent_to &&
          sent_to_count == o.sent_to_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, status, client_note, clock_paused, sent_to, sent_to_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
