=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.54.6-dev.10522

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # One position in a person summary (WINAD-10522). Lists are ranked by the lowest non-null position-type ord (unranked last), then sport name, school name, title and position ID.
  class PersonAssignment < ApiModelBase
    attr_accessor :position_id

    # Position season, expressed as its ending year
    attr_accessor :year

    attr_accessor :school_id

    attr_accessor :school_name

    attr_accessor :school_short_name

    attr_accessor :sport_id

    # Sport display name
    attr_accessor :sport_name

    # Free-text title, otherwise the position-type labels joined with commas
    attr_accessor :title

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'position_id' => :'position_id',
        :'year' => :'year',
        :'school_id' => :'school_id',
        :'school_name' => :'school_name',
        :'school_short_name' => :'school_short_name',
        :'sport_id' => :'sport_id',
        :'sport_name' => :'sport_name',
        :'title' => :'title'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'position_id' => :'Integer',
        :'year' => :'Integer',
        :'school_id' => :'Integer',
        :'school_name' => :'String',
        :'school_short_name' => :'String',
        :'sport_id' => :'Integer',
        :'sport_name' => :'String',
        :'title' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'school_name',
        :'school_short_name',
        :'sport_name',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::PersonAssignment` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::PersonAssignment`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'position_id')
        self.position_id = attributes[:'position_id']
      else
        self.position_id = nil
      end

      if attributes.key?(:'year')
        self.year = attributes[:'year']
      else
        self.year = nil
      end

      if attributes.key?(:'school_id')
        self.school_id = attributes[:'school_id']
      else
        self.school_id = nil
      end

      if attributes.key?(:'school_name')
        self.school_name = attributes[:'school_name']
      else
        self.school_name = nil
      end

      if attributes.key?(:'school_short_name')
        self.school_short_name = attributes[:'school_short_name']
      else
        self.school_short_name = nil
      end

      if attributes.key?(:'sport_id')
        self.sport_id = attributes[:'sport_id']
      else
        self.sport_id = nil
      end

      if attributes.key?(:'sport_name')
        self.sport_name = attributes[:'sport_name']
      else
        self.sport_name = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @position_id.nil?
        invalid_properties.push('invalid value for "position_id", position_id cannot be nil.')
      end

      if @year.nil?
        invalid_properties.push('invalid value for "year", year cannot be nil.')
      end

      if @school_id.nil?
        invalid_properties.push('invalid value for "school_id", school_id cannot be nil.')
      end

      if @sport_id.nil?
        invalid_properties.push('invalid value for "sport_id", sport_id cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @position_id.nil?
      return false if @year.nil?
      return false if @school_id.nil?
      return false if @sport_id.nil?
      return false if @title.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] position_id Value to be assigned
    def position_id=(position_id)
      if position_id.nil?
        fail ArgumentError, 'position_id cannot be nil'
      end

      @position_id = position_id
    end

    # Custom attribute writer method with validation
    # @param [Object] year Value to be assigned
    def year=(year)
      if year.nil?
        fail ArgumentError, 'year cannot be nil'
      end

      @year = year
    end

    # Custom attribute writer method with validation
    # @param [Object] school_id Value to be assigned
    def school_id=(school_id)
      if school_id.nil?
        fail ArgumentError, 'school_id cannot be nil'
      end

      @school_id = school_id
    end

    # Custom attribute writer method with validation
    # @param [Object] sport_id Value to be assigned
    def sport_id=(sport_id)
      if sport_id.nil?
        fail ArgumentError, 'sport_id cannot be nil'
      end

      @sport_id = sport_id
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      @title = title
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          position_id == o.position_id &&
          year == o.year &&
          school_id == o.school_id &&
          school_name == o.school_name &&
          school_short_name == o.school_short_name &&
          sport_id == o.sport_id &&
          sport_name == o.sport_name &&
          title == o.title
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [position_id, year, school_id, school_name, school_short_name, sport_id, sport_name, title].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
