=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.27

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class RawContractBackTo < ApiModelBase
    # Discriminator for the back-link target: 'coach' for a coach contract, 'game' for a game contract.
    attr_accessor :type

    # Coach id when type is 'coach'. Unused for 'game' (use home_school_id / away_school_id instead).
    attr_accessor :id

    # Coach name when type is 'coach'. Unused for 'game'.
    attr_accessor :name

    # Representative position title for the coach contract (matches the coach profile sidebar contract row).
    attr_accessor :position_title

    # Representative position group for the coach contract.
    attr_accessor :position_group

    # Sport for the coach (representative position) or game contract.
    attr_accessor :sport

    # Coach contract start date.
    attr_accessor :contract_start_on

    # Coach contract end date.
    attr_accessor :contract_end_on

    # Home school id when type is 'game'.
    attr_accessor :home_school_id

    # Home school name when type is 'game'.
    attr_accessor :home_school_name

    # Away school id when type is 'game'.
    attr_accessor :away_school_id

    # Away school name when type is 'game'.
    attr_accessor :away_school_name

    # Season year for the game contract (falls back to game_date year).
    attr_accessor :season_year

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'id' => :'id',
        :'name' => :'name',
        :'position_title' => :'position_title',
        :'position_group' => :'position_group',
        :'sport' => :'sport',
        :'contract_start_on' => :'contract_start_on',
        :'contract_end_on' => :'contract_end_on',
        :'home_school_id' => :'home_school_id',
        :'home_school_name' => :'home_school_name',
        :'away_school_id' => :'away_school_id',
        :'away_school_name' => :'away_school_name',
        :'season_year' => :'season_year'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'id' => :'Integer',
        :'name' => :'String',
        :'position_title' => :'String',
        :'position_group' => :'String',
        :'sport' => :'String',
        :'contract_start_on' => :'Date',
        :'contract_end_on' => :'Date',
        :'home_school_id' => :'Integer',
        :'home_school_name' => :'String',
        :'away_school_id' => :'Integer',
        :'away_school_name' => :'String',
        :'season_year' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'id',
        :'name',
        :'position_title',
        :'position_group',
        :'sport',
        :'contract_start_on',
        :'contract_end_on',
        :'home_school_id',
        :'home_school_name',
        :'away_school_id',
        :'away_school_name',
        :'season_year'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::RawContractBackTo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::RawContractBackTo`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'position_title')
        self.position_title = attributes[:'position_title']
      end

      if attributes.key?(:'position_group')
        self.position_group = attributes[:'position_group']
      end

      if attributes.key?(:'sport')
        self.sport = attributes[:'sport']
      end

      if attributes.key?(:'contract_start_on')
        self.contract_start_on = attributes[:'contract_start_on']
      end

      if attributes.key?(:'contract_end_on')
        self.contract_end_on = attributes[:'contract_end_on']
      end

      if attributes.key?(:'home_school_id')
        self.home_school_id = attributes[:'home_school_id']
      end

      if attributes.key?(:'home_school_name')
        self.home_school_name = attributes[:'home_school_name']
      end

      if attributes.key?(:'away_school_id')
        self.away_school_id = attributes[:'away_school_id']
      end

      if attributes.key?(:'away_school_name')
        self.away_school_name = attributes[:'away_school_name']
      end

      if attributes.key?(:'season_year')
        self.season_year = attributes[:'season_year']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          id == o.id &&
          name == o.name &&
          position_title == o.position_title &&
          position_group == o.position_group &&
          sport == o.sport &&
          contract_start_on == o.contract_start_on &&
          contract_end_on == o.contract_end_on &&
          home_school_id == o.home_school_id &&
          home_school_name == o.home_school_name &&
          away_school_id == o.away_school_id &&
          away_school_name == o.away_school_name &&
          season_year == o.season_year
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, id, name, position_title, position_group, sport, contract_start_on, contract_end_on, home_school_id, home_school_name, away_school_id, away_school_name, season_year].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
