=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.55.4

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # Only entities referenced by this page, each once and ordered by ID. Missing associations have no entry; clients must tolerate unresolved nullable IDs. Empty result pages contain four empty arrays.
  class ReconciliationIncluded < ApiModelBase
    attr_accessor :coaches

    attr_accessor :schools

    attr_accessor :sports

    attr_accessor :position_types

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'coaches' => :'coaches',
        :'schools' => :'schools',
        :'sports' => :'sports',
        :'position_types' => :'position_types'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'coaches' => :'Array<ReconciliationCoach>',
        :'schools' => :'Array<ReconciliationSchool>',
        :'sports' => :'Array<ReconciliationSport>',
        :'position_types' => :'Array<ReconciliationPositionType>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::ReconciliationIncluded` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::ReconciliationIncluded`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'coaches')
        if (value = attributes[:'coaches']).is_a?(Array)
          self.coaches = value
        end
      else
        self.coaches = nil
      end

      if attributes.key?(:'schools')
        if (value = attributes[:'schools']).is_a?(Array)
          self.schools = value
        end
      else
        self.schools = nil
      end

      if attributes.key?(:'sports')
        if (value = attributes[:'sports']).is_a?(Array)
          self.sports = value
        end
      else
        self.sports = nil
      end

      if attributes.key?(:'position_types')
        if (value = attributes[:'position_types']).is_a?(Array)
          self.position_types = value
        end
      else
        self.position_types = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @coaches.nil?
        invalid_properties.push('invalid value for "coaches", coaches cannot be nil.')
      end

      if @schools.nil?
        invalid_properties.push('invalid value for "schools", schools cannot be nil.')
      end

      if @sports.nil?
        invalid_properties.push('invalid value for "sports", sports cannot be nil.')
      end

      if @position_types.nil?
        invalid_properties.push('invalid value for "position_types", position_types cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @coaches.nil?
      return false if @schools.nil?
      return false if @sports.nil?
      return false if @position_types.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] coaches Value to be assigned
    def coaches=(coaches)
      if coaches.nil?
        fail ArgumentError, 'coaches cannot be nil'
      end

      @coaches = coaches
    end

    # Custom attribute writer method with validation
    # @param [Object] schools Value to be assigned
    def schools=(schools)
      if schools.nil?
        fail ArgumentError, 'schools cannot be nil'
      end

      @schools = schools
    end

    # Custom attribute writer method with validation
    # @param [Object] sports Value to be assigned
    def sports=(sports)
      if sports.nil?
        fail ArgumentError, 'sports cannot be nil'
      end

      @sports = sports
    end

    # Custom attribute writer method with validation
    # @param [Object] position_types Value to be assigned
    def position_types=(position_types)
      if position_types.nil?
        fail ArgumentError, 'position_types cannot be nil'
      end

      @position_types = position_types
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          coaches == o.coaches &&
          schools == o.schools &&
          sports == o.sports &&
          position_types == o.position_types
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [coaches, schools, sports, position_types].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
