=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.44.1

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class RecruitingChartData < ApiModelBase
    attr_accessor :years

    attr_accessor :recruit_rankings

    attr_accessor :conf_recruit_rankings

    attr_accessor :recruiting_budgets_dollars

    attr_accessor :conf_recruiting_budgets_dollars

    attr_accessor :sport_budgets_dollars

    attr_accessor :conf_sport_budgets_dollars

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'years' => :'years',
        :'recruit_rankings' => :'recruit_rankings',
        :'conf_recruit_rankings' => :'conf_recruit_rankings',
        :'recruiting_budgets_dollars' => :'recruiting_budgets_dollars',
        :'conf_recruiting_budgets_dollars' => :'conf_recruiting_budgets_dollars',
        :'sport_budgets_dollars' => :'sport_budgets_dollars',
        :'conf_sport_budgets_dollars' => :'conf_sport_budgets_dollars'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'years' => :'Array<Integer>',
        :'recruit_rankings' => :'Array<Integer>',
        :'conf_recruit_rankings' => :'Array<Float>',
        :'recruiting_budgets_dollars' => :'Array<Float>',
        :'conf_recruiting_budgets_dollars' => :'Array<Float>',
        :'sport_budgets_dollars' => :'Array<Float>',
        :'conf_sport_budgets_dollars' => :'Array<Float>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::RecruitingChartData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::RecruitingChartData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'years')
        if (value = attributes[:'years']).is_a?(Array)
          self.years = value
        end
      else
        self.years = nil
      end

      if attributes.key?(:'recruit_rankings')
        if (value = attributes[:'recruit_rankings']).is_a?(Array)
          self.recruit_rankings = value
        end
      else
        self.recruit_rankings = nil
      end

      if attributes.key?(:'conf_recruit_rankings')
        if (value = attributes[:'conf_recruit_rankings']).is_a?(Array)
          self.conf_recruit_rankings = value
        end
      else
        self.conf_recruit_rankings = nil
      end

      if attributes.key?(:'recruiting_budgets_dollars')
        if (value = attributes[:'recruiting_budgets_dollars']).is_a?(Array)
          self.recruiting_budgets_dollars = value
        end
      else
        self.recruiting_budgets_dollars = nil
      end

      if attributes.key?(:'conf_recruiting_budgets_dollars')
        if (value = attributes[:'conf_recruiting_budgets_dollars']).is_a?(Array)
          self.conf_recruiting_budgets_dollars = value
        end
      else
        self.conf_recruiting_budgets_dollars = nil
      end

      if attributes.key?(:'sport_budgets_dollars')
        if (value = attributes[:'sport_budgets_dollars']).is_a?(Array)
          self.sport_budgets_dollars = value
        end
      else
        self.sport_budgets_dollars = nil
      end

      if attributes.key?(:'conf_sport_budgets_dollars')
        if (value = attributes[:'conf_sport_budgets_dollars']).is_a?(Array)
          self.conf_sport_budgets_dollars = value
        end
      else
        self.conf_sport_budgets_dollars = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @years.nil?
        invalid_properties.push('invalid value for "years", years cannot be nil.')
      end

      if @recruit_rankings.nil?
        invalid_properties.push('invalid value for "recruit_rankings", recruit_rankings cannot be nil.')
      end

      if @conf_recruit_rankings.nil?
        invalid_properties.push('invalid value for "conf_recruit_rankings", conf_recruit_rankings cannot be nil.')
      end

      if @recruiting_budgets_dollars.nil?
        invalid_properties.push('invalid value for "recruiting_budgets_dollars", recruiting_budgets_dollars cannot be nil.')
      end

      if @conf_recruiting_budgets_dollars.nil?
        invalid_properties.push('invalid value for "conf_recruiting_budgets_dollars", conf_recruiting_budgets_dollars cannot be nil.')
      end

      if @sport_budgets_dollars.nil?
        invalid_properties.push('invalid value for "sport_budgets_dollars", sport_budgets_dollars cannot be nil.')
      end

      if @conf_sport_budgets_dollars.nil?
        invalid_properties.push('invalid value for "conf_sport_budgets_dollars", conf_sport_budgets_dollars cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @years.nil?
      return false if @recruit_rankings.nil?
      return false if @conf_recruit_rankings.nil?
      return false if @recruiting_budgets_dollars.nil?
      return false if @conf_recruiting_budgets_dollars.nil?
      return false if @sport_budgets_dollars.nil?
      return false if @conf_sport_budgets_dollars.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] years Value to be assigned
    def years=(years)
      if years.nil?
        fail ArgumentError, 'years cannot be nil'
      end

      @years = years
    end

    # Custom attribute writer method with validation
    # @param [Object] recruit_rankings Value to be assigned
    def recruit_rankings=(recruit_rankings)
      if recruit_rankings.nil?
        fail ArgumentError, 'recruit_rankings cannot be nil'
      end

      @recruit_rankings = recruit_rankings
    end

    # Custom attribute writer method with validation
    # @param [Object] conf_recruit_rankings Value to be assigned
    def conf_recruit_rankings=(conf_recruit_rankings)
      if conf_recruit_rankings.nil?
        fail ArgumentError, 'conf_recruit_rankings cannot be nil'
      end

      @conf_recruit_rankings = conf_recruit_rankings
    end

    # Custom attribute writer method with validation
    # @param [Object] recruiting_budgets_dollars Value to be assigned
    def recruiting_budgets_dollars=(recruiting_budgets_dollars)
      if recruiting_budgets_dollars.nil?
        fail ArgumentError, 'recruiting_budgets_dollars cannot be nil'
      end

      @recruiting_budgets_dollars = recruiting_budgets_dollars
    end

    # Custom attribute writer method with validation
    # @param [Object] conf_recruiting_budgets_dollars Value to be assigned
    def conf_recruiting_budgets_dollars=(conf_recruiting_budgets_dollars)
      if conf_recruiting_budgets_dollars.nil?
        fail ArgumentError, 'conf_recruiting_budgets_dollars cannot be nil'
      end

      @conf_recruiting_budgets_dollars = conf_recruiting_budgets_dollars
    end

    # Custom attribute writer method with validation
    # @param [Object] sport_budgets_dollars Value to be assigned
    def sport_budgets_dollars=(sport_budgets_dollars)
      if sport_budgets_dollars.nil?
        fail ArgumentError, 'sport_budgets_dollars cannot be nil'
      end

      @sport_budgets_dollars = sport_budgets_dollars
    end

    # Custom attribute writer method with validation
    # @param [Object] conf_sport_budgets_dollars Value to be assigned
    def conf_sport_budgets_dollars=(conf_sport_budgets_dollars)
      if conf_sport_budgets_dollars.nil?
        fail ArgumentError, 'conf_sport_budgets_dollars cannot be nil'
      end

      @conf_sport_budgets_dollars = conf_sport_budgets_dollars
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          years == o.years &&
          recruit_rankings == o.recruit_rankings &&
          conf_recruit_rankings == o.conf_recruit_rankings &&
          recruiting_budgets_dollars == o.recruiting_budgets_dollars &&
          conf_recruiting_budgets_dollars == o.conf_recruiting_budgets_dollars &&
          sport_budgets_dollars == o.sport_budgets_dollars &&
          conf_sport_budgets_dollars == o.conf_sport_budgets_dollars
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [years, recruit_rankings, conf_recruit_rankings, recruiting_budgets_dollars, conf_recruiting_budgets_dollars, sport_budgets_dollars, conf_sport_budgets_dollars].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
