=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.53.43-dev.10147

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  # One school's primary scheduling contact.
  class SchedulingContact < ApiModelBase
    attr_accessor :id

    attr_accessor :school

    attr_accessor :conference

    attr_accessor :person

    attr_accessor :cell_phone

    attr_accessor :office_phone

    attr_accessor :email

    attr_accessor :verified

    attr_accessor :verified_at

    # Miles from the viewer's school; null when either school lacks a location.
    attr_accessor :distance_miles

    attr_accessor :open_posts_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'school' => :'school',
        :'conference' => :'conference',
        :'person' => :'person',
        :'cell_phone' => :'cell_phone',
        :'office_phone' => :'office_phone',
        :'email' => :'email',
        :'verified' => :'verified',
        :'verified_at' => :'verified_at',
        :'distance_miles' => :'distance_miles',
        :'open_posts_count' => :'open_posts_count'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'school' => :'SchedulingContactSchool',
        :'conference' => :'SchedulingContactConference',
        :'person' => :'SchedulingContactPerson',
        :'cell_phone' => :'String',
        :'office_phone' => :'String',
        :'email' => :'String',
        :'verified' => :'Boolean',
        :'verified_at' => :'Date',
        :'distance_miles' => :'Integer',
        :'open_posts_count' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'cell_phone',
        :'office_phone',
        :'email',
        :'verified_at',
        :'distance_miles',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::SchedulingContact` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::SchedulingContact`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'school')
        self.school = attributes[:'school']
      else
        self.school = nil
      end

      if attributes.key?(:'conference')
        self.conference = attributes[:'conference']
      else
        self.conference = nil
      end

      if attributes.key?(:'person')
        self.person = attributes[:'person']
      else
        self.person = nil
      end

      if attributes.key?(:'cell_phone')
        self.cell_phone = attributes[:'cell_phone']
      else
        self.cell_phone = nil
      end

      if attributes.key?(:'office_phone')
        self.office_phone = attributes[:'office_phone']
      else
        self.office_phone = nil
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      else
        self.email = nil
      end

      if attributes.key?(:'verified')
        self.verified = attributes[:'verified']
      else
        self.verified = nil
      end

      if attributes.key?(:'verified_at')
        self.verified_at = attributes[:'verified_at']
      else
        self.verified_at = nil
      end

      if attributes.key?(:'distance_miles')
        self.distance_miles = attributes[:'distance_miles']
      else
        self.distance_miles = nil
      end

      if attributes.key?(:'open_posts_count')
        self.open_posts_count = attributes[:'open_posts_count']
      else
        self.open_posts_count = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @school.nil?
        invalid_properties.push('invalid value for "school", school cannot be nil.')
      end

      if @conference.nil?
        invalid_properties.push('invalid value for "conference", conference cannot be nil.')
      end

      if @person.nil?
        invalid_properties.push('invalid value for "person", person cannot be nil.')
      end

      if @verified.nil?
        invalid_properties.push('invalid value for "verified", verified cannot be nil.')
      end

      if @open_posts_count.nil?
        invalid_properties.push('invalid value for "open_posts_count", open_posts_count cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @school.nil?
      return false if @conference.nil?
      return false if @person.nil?
      return false if @verified.nil?
      return false if @open_posts_count.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] school Value to be assigned
    def school=(school)
      if school.nil?
        fail ArgumentError, 'school cannot be nil'
      end

      @school = school
    end

    # Custom attribute writer method with validation
    # @param [Object] conference Value to be assigned
    def conference=(conference)
      if conference.nil?
        fail ArgumentError, 'conference cannot be nil'
      end

      @conference = conference
    end

    # Custom attribute writer method with validation
    # @param [Object] person Value to be assigned
    def person=(person)
      if person.nil?
        fail ArgumentError, 'person cannot be nil'
      end

      @person = person
    end

    # Custom attribute writer method with validation
    # @param [Object] verified Value to be assigned
    def verified=(verified)
      if verified.nil?
        fail ArgumentError, 'verified cannot be nil'
      end

      @verified = verified
    end

    # Custom attribute writer method with validation
    # @param [Object] open_posts_count Value to be assigned
    def open_posts_count=(open_posts_count)
      if open_posts_count.nil?
        fail ArgumentError, 'open_posts_count cannot be nil'
      end

      @open_posts_count = open_posts_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          school == o.school &&
          conference == o.conference &&
          person == o.person &&
          cell_phone == o.cell_phone &&
          office_phone == o.office_phone &&
          email == o.email &&
          verified == o.verified &&
          verified_at == o.verified_at &&
          distance_miles == o.distance_miles &&
          open_posts_count == o.open_posts_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, school, conference, person, cell_phone, office_phone, email, verified, verified_at, distance_miles, open_posts_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
