=begin
#Winthrop Intelligence Internal API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.43.2

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module WinthropClient
  class Sport < ApiModelBase
    attr_accessor :id

    attr_accessor :name

    attr_accessor :name_aka

    attr_accessor :name_display

    attr_accessor :gender_code

    attr_accessor :emerging

    attr_accessor :meet_sport

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :ncaa_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'name_aka' => :'name_aka',
        :'name_display' => :'name_display',
        :'gender_code' => :'gender_code',
        :'emerging' => :'emerging',
        :'meet_sport' => :'meet_sport',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'ncaa_id' => :'ncaa_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'name' => :'String',
        :'name_aka' => :'String',
        :'name_display' => :'String',
        :'gender_code' => :'String',
        :'emerging' => :'Boolean',
        :'meet_sport' => :'Boolean',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'ncaa_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WinthropClient::Sport` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WinthropClient::Sport`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'name_aka')
        self.name_aka = attributes[:'name_aka']
      end

      if attributes.key?(:'name_display')
        self.name_display = attributes[:'name_display']
      end

      if attributes.key?(:'gender_code')
        self.gender_code = attributes[:'gender_code']
      end

      if attributes.key?(:'emerging')
        self.emerging = attributes[:'emerging']
      end

      if attributes.key?(:'meet_sport')
        self.meet_sport = attributes[:'meet_sport']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'ncaa_id')
        self.ncaa_id = attributes[:'ncaa_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      gender_code_validator = EnumAttributeValidator.new('String', ["M", "W"])
      return false unless gender_code_validator.valid?(@gender_code)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gender_code Object to be assigned
    def gender_code=(gender_code)
      validator = EnumAttributeValidator.new('String', ["M", "W"])
      unless validator.valid?(gender_code)
        fail ArgumentError, "invalid value for \"gender_code\", must be one of #{validator.allowable_values}."
      end
      @gender_code = gender_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          name_aka == o.name_aka &&
          name_display == o.name_display &&
          gender_code == o.gender_code &&
          emerging == o.emerging &&
          meet_sport == o.meet_sport &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          ncaa_id == o.ncaa_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, name_aka, name_display, gender_code, emerging, meet_sport, created_at, updated_at, ncaa_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end
  end
end
